<Workspace Version="1.3.0.875" X="51.4685214525374" Y="212.22518249992" zoom="1.10476425630303" ScaleFactor="1" Name="GetBuiltInParameterName" Description="Get BuiltIn Parameter names by parameter names and element." ID="1eae61a3-f857-4ccd-876d-f6c5cee6c79e" Category="Quasar.Revit.BuiltInParameter">
  <NamespaceResolutionMap>
    <ClassMap partialName="FamilyType" resolvedName="Revit.Elements.FamilyType" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Document.Phases" resolvedName="Revit.Application.Document" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="fc425bea-b055-4489-86dc-f0a83f99ed8b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="-0.905170487092335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># dynamo version - 1.3.0
# author - min.naung@mgjean

import clr
clr.AddReference("RevitAPI")

import System
from Autodesk.Revit.DB import *

elements = UnwrapElement(IN[0]);
params = IN[1];
if not isinstance(params,list):
	params = [params];
	
bIns = [i for i in System.Enum.GetValues(BuiltInParameter)];

associate = [];
for i in set(bIns):
	for p in params:
		if elements.get_Parameter(i) and elements.get_Parameter(i).Definition.Name == p:
			associate.extend([p,i])

OUT = associate;</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bdbcd0a3-b786-4bb8-a2a6-bd7b3942da0b" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Element" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="7de9ae2c-bba2-4b9a-8c6d-22af978cb4c0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ParameterNames:string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="19b4a8ff-51fa-47af-99c8-e8e972ea6832" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="NameList" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fc425bea-b055-4489-86dc-f0a83f99ed8b" start_index="0" end="19b4a8ff-51fa-47af-99c8-e8e972ea6832" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bdbcd0a3-b786-4bb8-a2a6-bd7b3942da0b" start_index="0" end="fc425bea-b055-4489-86dc-f0a83f99ed8b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7de9ae2c-bba2-4b9a-8c6d-22af978cb4c0" start_index="0" end="fc425bea-b055-4489-86dc-f0a83f99ed8b" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="d17e5e26-62e4-4948-81fe-9c383968f6ef" text="IN[0] = element&#xD;&#xA;IN[1] = parameter names" x="241.454147113953" y="-46.9147951731685" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>