<Workspace Version="1.3.0.875" X="172.675546692765" Y="91.341261838553" zoom="1.33823125" ScaleFactor="1" Name="PlanViewCropByRoom" Description="Crop floor or ceiling plan views by given room. Offset is a distance of crop box from room boundary and unit is millimeter. View scale is 1:50 by default. " ID="a66c1b82-723d-48e0-993e-58cdd2d915b5" Category="Quasar.Revit.Views">
  <NamespaceResolutionMap>
    <ClassMap partialName="Level" resolvedName="Revit.Elements.Level" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Revit.Room" resolvedName="Revit.Elements.Room" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="edd05970-dedf-4cbd-99d2-39183e300748" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script># dynamo version - 1.3.0
# author - min.naung@mgjean

import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument


Views = IN[0];
Offset = IN[2]/304.8;
Rooms = IN[1];
run = IN[3];
result = [];

if not isinstance(Views,list):
	Views = UnwrapElement([Views]);
else:
	Views = UnwrapElement(Views);

if not isinstance(Rooms,list):
	Rooms = UnwrapElement([Rooms]);
else:
	Rooms = UnwrapElement(Rooms);
	

def crop_box(bbox, offset):
	minX = bbox.Min.X - offset;
	minY = bbox.Min.Y - offset;
	minZ = bbox.Min.Z - offset;
	maxX = bbox.Max.X + offset;
	maxY = bbox.Max.Y + offset;
	maxZ = bbox.Max.Z + offset;
	
	newbox = BoundingBoxXYZ();
	newbox.Min = XYZ(minX,minY, minZ);
	newbox.Max = XYZ(maxX, maxY, maxZ);
	return newbox;

if run:
	TransactionManager.Instance.EnsureInTransaction(doc);
	for r,v in zip(Rooms,Views):
		v.CropBox = crop_box(r.BoundingBox[doc.ActiveView],Offset);
		v.CropBoxActive = True;
		v.CropBoxVisible = False;
		v.Scale = 50;
		result.append(v);
	TransactionManager.Instance.TransactionTaskDone();
	OUT = result;
else:
	OUT = "Run Forest Run";</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="8c776766-6984-4775-9d1d-e197488b22e6" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="93073557-56af-4d94-a16e-76b3bcf6be7a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="29" y="-2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="91a7e738-79bf-469d-801e-1a617555e654" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="29" y="63" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e540af32-e070-41e6-911f-2b6e1bb4742c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="12" y="130" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Offset:double=500;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dc0b3d06-b79a-4c7a-8e5b-d4c6418c9711" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="28" y="201" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Run:bool=false;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="edd05970-dedf-4cbd-99d2-39183e300748" start_index="0" end="8c776766-6984-4775-9d1d-e197488b22e6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="93073557-56af-4d94-a16e-76b3bcf6be7a" start_index="0" end="edd05970-dedf-4cbd-99d2-39183e300748" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="91a7e738-79bf-469d-801e-1a617555e654" start_index="0" end="edd05970-dedf-4cbd-99d2-39183e300748" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e540af32-e070-41e6-911f-2b6e1bb4742c" start_index="0" end="edd05970-dedf-4cbd-99d2-39183e300748" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc0b3d06-b79a-4c7a-8e5b-d4c6418c9711" start_index="0" end="edd05970-dedf-4cbd-99d2-39183e300748" end_index="3" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>