<Workspace Version="1.3.2.2480" X="146.4" Y="197.6" zoom="1" ScaleFactor="1" Name="PolygonsByCurves" Description="Create polygon by curve and number of side, returns value [ polygon, [line-segments] ]" ID="a00c3be9-e031-44d9-afed-485a4bd806cc" Category="Quasar.DynamoNodes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="cbb7e034-573e-4a53-8163-63e271b4dce1" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># dynamo version - 1.3.2'
# author - min.naung/mgjean @https://twentytwo.space/contact

import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

def make_list(l):
	if not isinstance(l,list):
		return [l]
	return l
		
curve_list = make_list(IN[0])
side_list =make_list(IN[1])

def getPoints(curve,side):
	base = float(1/float(side))
	increment = 0
	points = []
	for i in range(int(side)):
		increment += base
		point = Curve.PointAtParameter(curve,increment)
		points.append(point)
	return points

def lineSegments(points):
	line_segments = []
	for num,point in enumerate(points):
		if num == len(points):
			break;
		if num == len(points)-1:
			next = num + 1
			line = Line.ByStartPointEndPoint(point,points[0])
		
		else:
			next = num + 1
			line = Line.ByStartPointEndPoint(point, points[next])
		line_segments.append(line);
	return line_segments

polygons, segments = [],[]
for curve,side in zip(curve_list,side_list):
	points = getPoints(curve,side)
	polygons.append(Polygon.ByPoints(points))
	segments.append(lineSegments(points))

OUT = polygons, segments



</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e64e42cd-44f1-49be-8902-0e1e9be19ea6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Curve or Curves&#xD;&#xA;Curve_" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="f9b83431-0568-4faa-9ba2-b8f134c29ced" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-18.4000000000001" y="108.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// int or int list&#xD;&#xA;NumberOfSide" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="3bec2c50-5a66-40cf-b322-63f277cd147e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="537.8" y="-28" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// return polygon&#xD;&#xA;Polygons" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="24100ce1-82a7-4869-967b-1f6ddaad71af" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="404.4" y="44.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="i[0];&#xA;i[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="95a82073-3f12-423f-a95e-0731ad31a039" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="568.4" y="87.1999999999998" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// line segments of polygon&#xD;&#xA;LineSegments" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="cbb7e034-573e-4a53-8163-63e271b4dce1" start_index="0" end="24100ce1-82a7-4869-967b-1f6ddaad71af" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e64e42cd-44f1-49be-8902-0e1e9be19ea6" start_index="0" end="cbb7e034-573e-4a53-8163-63e271b4dce1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f9b83431-0568-4faa-9ba2-b8f134c29ced" start_index="0" end="cbb7e034-573e-4a53-8163-63e271b4dce1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24100ce1-82a7-4869-967b-1f6ddaad71af" start_index="0" end="3bec2c50-5a66-40cf-b322-63f277cd147e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="24100ce1-82a7-4869-967b-1f6ddaad71af" start_index="1" end="95a82073-3f12-423f-a95e-0731ad31a039" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.596237824330502" eyeY="4.90230775033181" eyeZ="1.68195700042881" lookX="-0.000757694327831349" lookY="-0.0302904853343957" lookZ="-0.00685145237445828" upX="-0.0994574427604675" upY="0.425779283046722" upZ="-0.899344325065613" />
  </Cameras>
</Workspace>