<Workspace Version="1.3.2.2480" X="-217.386" Y="201.994" zoom="1.1575" ScaleFactor="1" Name="GetLinkDocument" Description="Get all link documents from current document.&#xD;&#xA;*Note : index zero is link document name and index one is link document.  " ID="b3def24f-9e36-46ba-aa11-a6bc9e0f878e" Category="Quasar.Revit.RevitLinkDocument">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="ebb878b9-e81b-4c2f-b1fc-591986c84469" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script># dynamo version - 1.3.0 
# author - min.naung@mgjean https://twentytwopaths.wordpress.com/contact/


import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument;
link_docs = FilteredElementCollector(doc).OfClass(RevitLinkInstance);

OUT = [[i.Name.split(":")[0],i.GetLinkDocument()] for i in link_docs];
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4b6b163a-1e4e-4a5a-be10-586851d99eea" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="445.55464362851" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="LinkDocs" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ebb878b9-e81b-4c2f-b1fc-591986c84469" start_index="0" end="4b6b163a-1e4e-4a5a-be10-586851d99eea" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>