<Workspace Version="1.3.2.2480" X="-47.7942776588696" Y="320.889119451276" zoom="0.867977507649019" ScaleFactor="1" Name="UIElementSelector" Description="This node [a simple window form interface] can select elements by category or parameter name and value." ID="62cd8713-ea9d-4beb-b23a-8d631ebf4c61" Category="Quasar.Revit.Selection">
  <NamespaceResolutionMap>
    <ClassMap partialName="RenderType" resolvedName="Analyze.Render.RenderType" assemblyName="SimpleRaaS.dll" />
    <ClassMap partialName="RenderQuality" resolvedName="Analyze.Render.RenderQuality" assemblyName="SimpleRaaS.dll" />
    <ClassMap partialName="Directory" resolvedName="DSCore.IO.Directory" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="ec475fa6-0d87-4495-b634-8623c7a89ff1" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="418.6" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <PythonNodeModels.PythonNode guid="551f2051-c81d-4473-a641-df5a37fa15a7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="246.685373709439" y="101.338548707175" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" inputcount="0">
      <Script># dynamo version - 1.3.0
# author - min.naung@mgjean https://twentytwopaths.wordpress.com/contact/

import clr,sys
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")
clr.AddReference("System.Windows.Forms")
clr.AddReference("System.Drawing")

sys.path.append(r"C:\Program Files (x86)\IronPython 2.7\Lib")

import os,System

version = ["2.0","1.3","1.2","1.1","1.0","0.9","0.8","0.7"]

appdata = os.getenv("AppData");
qpath = r"\Dynamo\Dynamo Revit\%s\packages\Quasar"

for i in version:
	if os.path.exists(os.path.join(appdata+qpath %i)):
		ipath = os.path.join(appdata+qpath %i)

from System.Collections.Generic import List
from System.Windows.Forms import Application, Button,ComboBox,CheckBox, Form as _Form, Label, TextBox, MessageBox, MessageBoxButtons, MessageBoxIcon
from System.Drawing import Font, Icon, Point as _Point, FontStyle,Size, Color as _Color

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc = DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

DictNumericRules = {"greater than":FilterNumericGreater(),"less than":FilterNumericLess(),"greater than or equal":FilterNumericGreaterOrEqual(),"less than or equal":FilterNumericLessOrEqual(),"equal":FilterNumericEquals()}
DictStringRules = {"begins with":FilterStringBeginsWith(),"contains":FilterStringContains(),"ends with":FilterStringEndsWith(),"equals":FilterStringEquals()}

rules = tuple(DictNumericRules.keys() + DictStringRules.keys())
pure = []
res = []
name = []
collect = FilteredElementCollector(doc,doc.ActiveView.Id).ToElements()
cate = [i.Category.Name for i in collect if i.Category]
[pure.append(i) for i in cate if i not in pure]
elems = ''

for i in doc.Settings.Categories:
	if i.Name in pure:
		res.append(i)	

name = tuple([i.Name for i in res])
ans = "Not Selected!"
class DropDownForm(_Form):
	def __init__(self):
		self.Text = "QuasarÂ®"
		self.Icon = Icon(r"%s\extra\icon.ico" %ipath)
		self.Size = Size(300,280)
		
		font = Font("Georgia", 10 )
		fontone = Font("Georgia", 9 )
		fonttwo = Font("Georgia", 9,FontStyle.Bold )
		
		self.cb = ComboBox()
		self.cb.Size = Size(245,100)
		self.cb.Location = _Point(20,20)
		self.cb.Text = "Select Elements By Category"
		self.cb.Font = font
		self.cb.Items.AddRange(name)
		
		self.chkbox = CheckBox()
		self.chkbox.Location = _Point(90,60)
		self.chkbox.Size = Size(120,20)
		self.chkbox.Font = fonttwo
		self.chkbox.Text = "  Add Filter"
		
		self.txtparam = TextBox()
		self.txtparam.Text = "Parameter Name ..."
		self.txtparam.Font = fontone
		self.txtparam.ForeColor = _Color.Gray
		self.txtparam.Size = Size(160,100)
		self.txtparam.Location = _Point(60,85)
		self.txtparam.Enabled = False
		
		self.cb_rules = ComboBox()
		self.cb_rules.Size = Size(160,100)
		self.cb_rules.Location = _Point(60,120)
		self.cb_rules.Font = fontone
		self.cb_rules.Items.AddRange(rules)
		self.cb_rules.Enabled = False
		
		self.txtvalue = TextBox()
		self.txtvalue.Text = "Parameter Value ..."
		self.txtvalue.Font = fontone
		self.txtvalue.ForeColor = _Color.Gray
		self.txtvalue.Size = Size(160,100)
		self.txtvalue.Location = _Point(60,155)
		self.txtvalue.Enabled = False
		
		self.okbtn = Button()
		self.okbtn.Font = fonttwo
		self.okbtn.Text = "Ok"
		self.okbtn.Location = _Point(100,190)
		
		self.Controls.Add(self.okbtn)
		self.Controls.Add(self.txtvalue)
		self.Controls.Add(self.txtparam)
		self.Controls.Add(self.chkbox)
		self.Controls.Add(self.cb_rules)
		self.Controls.Add(self.cb)
		
		self.txtparam.GotFocus += self.tb_focus
		self.txtvalue.GotFocus += self.tb_focus
		self.okbtn.Click += self.ok_click
		self.chkbox.CheckedChanged += self.chkstate
				
		self.CenterToScreen()
	
	def ok_click(self, sender, event):
		
		global ans, elems
		for i in res:
			if self.cb.SelectedItem == i.Name:
				elems = FilteredElementCollector(doc).OfCategoryId(i.Id).WhereElementIsNotElementType().ToElements();
					
				if str(self.chkbox.CheckState) == "Checked":
					builtInParams = [i for i in System.Enum.GetValues(BuiltInParameter)];
					bparamName = [c for c in builtInParams if elems[0].get_Parameter(c) and elems[0].get_Parameter(c).Definition.Name == str(self.txtparam.Text)][0]
						
						
					bipname = eval("BuiltInParameter."+str(bparamName));
					pvp = ParameterValueProvider(ElementId(bipname));
						
					if self.txtvalue.Text.isdigit():
						val = int(self.txtvalue.Text)/304.8;
						eval_rule = DictNumericRules[self.cb_rules.SelectedItem];
						rule = FilterDoubleRule(pvp,eval_rule,val,1E-6);
					if self.txtvalue.Text.isalpha():
						val = self.txtvalue.Text;
						eval_rule = DictStringRules[self.cb_rules.SelectedItem];
						rule = FilterStringRule(pvp,eval_rule,val,False);
								
					filter_rule = ElementParameterFilter(rule)
					prelist=[]
					for i in elems:
						prelist.append(i.Id);
						Icollection = List[ElementId](prelist);
			
					elems = FilteredElementCollector(doc,Icollection).WherePasses(filter_rule).ToElements();
						
					#MessageBox.Show("Incorrect value detected.","Error Message!",MessageBoxButtons.OK, MessageBoxIcon.Information)
			
		selected = uidoc.Selection
		icollect = List[ElementId]([i.Id for i in elems])
		selected.SetElementIds(icollect);
						
		ans = elems
		self.Close()
						
		
		#MessageBox.Show("Incorrect value detected.","Error Message!",MessageBoxButtons.OK, MessageBoxIcon.Information)


	def tb_focus(self, sender, event):
		sender.Text = ""
		sender.ForeColor = _Color.Black
	
	def chkstate(self, sender, event):
		if str(sender.CheckState) == "Checked":
			self.txtparam.Enabled = True
			self.cb_rules.Enabled = True
			self.txtvalue.Enabled = True
			
		else:
			self.txtparam.Enabled = False
			self.cb_rules.Enabled = False
			self.cb_rules.SelectedIndex = -1
			self.txtvalue.Enabled = False

	
Application.Run(DropDownForm())

OUT = ans</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="551f2051-c81d-4473-a641-df5a37fa15a7" start_index="0" end="ec475fa6-0d87-4495-b634-8623c7a89ff1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>