<Workspace Version="1.3.2.2480" X="-26.4" Y="272.6" zoom="1" ScaleFactor="1" Name="ViewDuplicate" Description="Duplicate views with given names." ID="fd0b4164-49bd-460d-8cc3-43d91c29131e" Category="Quasar.Revit.Views">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6f91c4e6-a9a5-4731-8e7d-55892b47f752" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script># dynamo version - 1.3.0
# author - min.naung@mgjean https://twentytwopaths.wordpress.com/contact/

import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
doc = DocumentManager.Instance.CurrentDBDocument

views = IN[0];
names = IN[1];
detailing = IN[2];
res = [];

if not isinstance(views,list):
	views = UnwrapElement([views]);
else:
	views = UnwrapElement(views);

if not isinstance(names,list):
	names = [names];

TransactionManager.Instance.EnsureInTransaction(doc);
for i,n in zip(views,names):
	if detailing:
		v = i.Duplicate(ViewDuplicateOption.WithDetailing);
	else:
		v = i.Duplicate(ViewDuplicateOption.Duplicate);
	dupview = doc.GetElement(v);
	dupview.Name = n;
	dupview.Scale = 25;
	dupview.CropBoxActive = True;
	dupview.CropBoxVisible = False;
	res.append(dupview);
TransactionManager.Instance.TransactionTaskDone();
OUT = res;

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e514d55c-be90-4af8-b841-50a45db8724a" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Views" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="3735a8d2-fbf7-4b78-98dc-7f2fb32e5b41" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="87.2000000000002" y="-44.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="View" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="972b7f3a-4444-40a4-88a4-8ecfe57a0678" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="92.8" y="37.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Names" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="639dda27-169b-4ea7-9578-2410638ad9e5" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="38.4" y="107.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Detailing:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6f91c4e6-a9a5-4731-8e7d-55892b47f752" start_index="0" end="e514d55c-be90-4af8-b841-50a45db8724a" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3735a8d2-fbf7-4b78-98dc-7f2fb32e5b41" start_index="0" end="6f91c4e6-a9a5-4731-8e7d-55892b47f752" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="972b7f3a-4444-40a4-88a4-8ecfe57a0678" start_index="0" end="6f91c4e6-a9a5-4731-8e7d-55892b47f752" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="639dda27-169b-4ea7-9578-2410638ad9e5" start_index="0" end="6f91c4e6-a9a5-4731-8e7d-55892b47f752" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>