<Workspace Version="1.3.2.2480" X="57.5999999999999" Y="157.6" zoom="1" ScaleFactor="1" Name="CreateBeamsByModelCurves" Description="Create beams by model curves." ID="fa6dbc4d-6949-40a7-901b-93e42971adbc" Category="Quasar.RevitNodes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4e7a7f25-71b4-4e10-93c9-ecef43522c96" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>
# dynamo version - 1.3.2
# author - 'min.naung/mgjean @https://twentytwo.space/contact'



# import common language runtime 
import clr

# clr.AddReference loads and imports .net assembly(dll) as python module
# load RevitAPI.dll and RevitServices.dll
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

# import all classes from Revit DB
from Autodesk.Revit.DB import *

# import document manager
from RevitServices.Persistence import DocumentManager
# import transaction manager
from RevitServices.Transactions import TransactionManager

# instantiate current document
doc = DocumentManager.Instance.CurrentDBDocument

# input model curves
lines = IN[0]
# empty list for return output
beams = []

# if input is a list 
if isinstance(lines, list):
	lines = UnwrapElement(lines)
# if not a list
else:
	lines = UnwrapElement([lines])

#current view level
level = doc.ActiveView.GenLevel

#structural framing symbol
sym=UnwrapElement(IN[1])

#transaction start
TransactionManager.Instance.EnsureInTransaction(doc)

for line in lines:
	
	#create beam
	beam = doc.Create.NewFamilyInstance(line.GeometryCurve, sym, 
		level, Structure.StructuralType.Beam)
	#append to output
	beams.append(beam)

#transaction end
TransactionManager.Instance.TransactionTaskDone()

#output
OUT = beams</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6d1df23e-194e-4c3c-9a87-e8fac330eb1c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Model Curves&#xD;&#xA;ModelCurves" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0aff1672-48fd-4e72-b76f-c26a49878631" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Family Type&#xD;&#xA;familyType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6999b92e-0ec9-483b-b7a3-b75ef93e76a2" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//Output&#xD;&#xA;Beams" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4e7a7f25-71b4-4e10-93c9-ecef43522c96" start_index="0" end="6999b92e-0ec9-483b-b7a3-b75ef93e76a2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6d1df23e-194e-4c3c-9a87-e8fac330eb1c" start_index="0" end="4e7a7f25-71b4-4e10-93c9-ecef43522c96" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0aff1672-48fd-4e72-b76f-c26a49878631" start_index="0" end="4e7a7f25-71b4-4e10-93c9-ecef43522c96" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>