<Workspace Version="1.3.2.2480" X="114.4" Y="243.2" zoom="1" ScaleFactor="1" Name="AllElementsOfWorkset" Description="Collect all elements from input workset." ID="d95914d3-d3e8-4568-a830-a25bd192237e" Category="Quasar.ElementUtility">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4c24d7ba-493b-47b8-9a4a-b6672f61add6" type="PythonNodeModels.PythonNode" nickname="AllElementsOfWorkset" x="217.2" y="-22.4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2
# author - min.naung/mgjean https://twentytwo.space/contact/

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

workset = IN[0]
filter = ElementWorksetFilter(workset.Id,False)
# collect user created worksets
elements = FilteredElementCollector(doc).WherePasses(filter).ToElements()
# elements output
OUT = elements</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="ea7cc4e6-5774-4445-9c22-105a115fb3fb" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Workset Element&#xD;&#xA;workset" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="27a05466-1536-429f-b10f-94507199e5da" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="429.8" y="-25.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// All elements of workset&#xD;&#xA;Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="4c24d7ba-493b-47b8-9a4a-b6672f61add6" start_index="0" end="27a05466-1536-429f-b10f-94507199e5da" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ea7cc4e6-5774-4445-9c22-105a115fb3fb" start_index="0" end="4c24d7ba-493b-47b8-9a4a-b6672f61add6" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="15121.8769685405" eyeY="23704.3131388975" eyeZ="7926.38589083202" lookX="112.73349855794" lookY="-18324.8822401903" lookZ="-7262.04042040637" upX="0.0128681529411369" upY="0.559192903470746" upZ="-0.828937698109959" />
  </Cameras>
</Workspace>