<Workspace Version="1.3.2.2480" X="228" Y="232" zoom="1" ScaleFactor="1" Name="RoomSolidGeometry" Description="Collect dynamo geometry and revit geometry from room." ID="700b827d-9fae-4244-9294-f4b97936e203" Category="Quasar.RoomUtility">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="26c830e0-41f3-4cbf-9484-c733c656e90e" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2'
# author - min.naung/mgjean @https://twentytwo.space/contact

import clr

clr.AddReference('RevitAPI')
clr.AddReference("RevitNodes")

import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

from Autodesk.Revit.DB import Reference


elems = IN[0];

if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

rvt = []
dyn = []

for e in elems:
	geoelem = e.GetGeometryObjectFromReference(Reference(e))
	geoobj = geoelem.GetEnumerator();
	for obj in geoobj:			
		rvt.append(obj)
		dyn.append(obj.ToProtoType())		

OUT = rvt,dyn




















</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="151dd138-0fc5-457f-809c-a8b70be461ec" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Room Elements&#xD;&#xA;Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b086226d-9b9f-4be1-a468-06cae69bcf9e" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="618.6" y="-12.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Revit type geometry&#xD;&#xA;RevitGeometry" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="741cc8d4-3407-4d88-8f5d-879cf27a6c56" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="620" y="57.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Dynamo type geometry&#xD;&#xA;DynamoGeometry" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="96c5c74a-80b0-4ddf-8a0f-385e741cb86f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="427.2" y="-8.19999999999999" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="i[0];&#xA;i[1];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="26c830e0-41f3-4cbf-9484-c733c656e90e" start_index="0" end="96c5c74a-80b0-4ddf-8a0f-385e741cb86f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="151dd138-0fc5-457f-809c-a8b70be461ec" start_index="0" end="26c830e0-41f3-4cbf-9484-c733c656e90e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96c5c74a-80b0-4ddf-8a0f-385e741cb86f" start_index="0" end="b086226d-9b9f-4be1-a468-06cae69bcf9e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="96c5c74a-80b0-4ddf-8a0f-385e741cb86f" start_index="1" end="741cc8d4-3407-4d88-8f5d-879cf27a6c56" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>