<Workspace Version="1.3.2.2480" X="-117.206698378997" Y="-65.5136524342421" zoom="0.583294539236839" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="eb1b0600-b12e-4710-b0e3-f617c4988717" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="188" y="207.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="8a99590c-60a5-4488-bea4-c25db02b8482" type="DSRevitNodesUI.Categories" nickname="Categories" x="-20.8" y="199.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="84177c39-9459-42d7-9eb3-c2d863f68f89" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="383.371893888796" y="563.018670271967" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4e727fd8-cac2-480b-b5a6-e659b53a45d0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Centroid" x="768.056135769221" y="405.893802896905" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Centroid">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="95587380-094b-4fc0-9641-68dd7fc3c935" type="PythonNodeModels.PythonNode" nickname="Python Script" x="789.374946104115" y="61.5626957670108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># import common language runtime 
import clr

# load RevitAPI.dll and RevitServices.dll
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

# import all classes from Revit DB
from Autodesk.Revit.DB import *

# import document manager
from RevitServices.Persistence import DocumentManager
# import transaction manager
from RevitServices.Transactions import TransactionManager

# instantiate current document
doc = DocumentManager.Instance.CurrentDBDocument

res = []

for i in UnwrapElement(IN[0]):
	point = i.Location.Point
	x = point.X
	y = point.Y
	z = point.Z
	res.append([x*304.8,y*304.8,z*304.8])

OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="601fde33-a410-412c-98ef-18f3ccd90e39" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Geometry.Translate" x="1180.93594637467" y="321.362931703909" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector,double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="564cd67d-125d-45c7-a654-6af2a129ae48" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Vector.ZAxis" x="1027.70970732326" y="312.15074481946" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="454b8de7-587a-4a1a-a2d0-2a8cc62a9107" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Z" x="951.488404255342" y="546.035291219648" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Z">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="34b75043-b3eb-4702-9e08-31165a55f3b6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1253" y="606" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="x&gt;1 ? -x: x;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="eb1b0600-b12e-4710-b0e3-f617c4988717" start_index="0" end="84177c39-9459-42d7-9eb3-c2d863f68f89" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eb1b0600-b12e-4710-b0e3-f617c4988717" start_index="0" end="95587380-094b-4fc0-9641-68dd7fc3c935" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8a99590c-60a5-4488-bea4-c25db02b8482" start_index="0" end="eb1b0600-b12e-4710-b0e3-f617c4988717" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="84177c39-9459-42d7-9eb3-c2d863f68f89" start_index="0" end="4e727fd8-cac2-480b-b5a6-e659b53a45d0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4e727fd8-cac2-480b-b5a6-e659b53a45d0" start_index="0" end="454b8de7-587a-4a1a-a2d0-2a8cc62a9107" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4e727fd8-cac2-480b-b5a6-e659b53a45d0" start_index="0" end="601fde33-a410-412c-98ef-18f3ccd90e39" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="564cd67d-125d-45c7-a654-6af2a129ae48" start_index="0" end="601fde33-a410-412c-98ef-18f3ccd90e39" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="454b8de7-587a-4a1a-a2d0-2a8cc62a9107" start_index="0" end="34b75043-b3eb-4702-9e08-31165a55f3b6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="34b75043-b3eb-4702-9e08-31165a55f3b6" start_index="0" end="601fde33-a410-412c-98ef-18f3ccd90e39" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-18459.1754845886" eyeY="8390.74700496436" eyeZ="2515.82610003657" lookX="15825.4103369776" lookY="-8326.88351041609" lookZ="-5607.37665708945" upX="0.228030638369259" upY="0.97029570334996" upZ="-0.0807974831798436" />
  </Cameras>
</Workspace>