<Workspace Version="1.3.2.2480" X="-43.7677079439723" Y="34.676007823802" zoom="0.818865791623838" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="eb1b0600-b12e-4710-b0e3-f617c4988717" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="188" y="207.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="8a99590c-60a5-4488-bea4-c25db02b8482" type="DSRevitNodesUI.Categories" nickname="Categories" x="-20.8" y="199.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <PythonNodeModels.PythonNode guid="2e4abb35-82a2-41a2-8555-1f6563109f98" type="PythonNodeModels.PythonNode" nickname="Python Script" x="567.79019711894" y="193.060396762322" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
clr.AddReference("RevitNodes")

import System,Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from Autodesk.DesignScript.Geometry import (Geometry,
Point as pt)
from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elems = IN[0];

if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

res = []

#TransactionManager.Instance.EnsureInTransaction(doc)

for e in elems:
	elevation = e.Level.Elevation * 304.8
	geoelem = e.GetGeometryObjectFromReference(Reference(e))
	geoobj = geoelem.GetEnumerator();
	for obj in geoobj:
		room_geometry = obj.ToProtoType()
		point = room_geometry.Centroid()
		newloc = pt.ByCoordinates(point.X,point.Y,elevation)
		#e.Location.Move(newloc.ToRevitType())
		res.append([point,newloc,newloc.ToRevitType()])

#TransactionManager.Instance.TransactionTaskDone()

OUT = res




















</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="eb1b0600-b12e-4710-b0e3-f617c4988717" start_index="0" end="2e4abb35-82a2-41a2-8555-1f6563109f98" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8a99590c-60a5-4488-bea4-c25db02b8482" start_index="0" end="eb1b0600-b12e-4710-b0e3-f617c4988717" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-21197.515625" eyeY="-879.966125488281" eyeZ="2814.25512695313" lookX="18691.166015625" lookY="-1039.45764160156" lookZ="-884.928771972656" upX="-0.159702301025391" upY="0.987136244773865" upZ="0.00756108108907938" />
  </Cameras>
</Workspace>