<Workspace Version="1.3.2.2480" X="325.732449164769" Y="29.9795119398368" zoom="0.793979681425324" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1e9641f2-179f-4231-9e28-fe44d426642c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="237.374275247223" y="-475.142908500233" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr

clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elements = IN[0]
todelete = []

if not isinstance(elements, list):
	elements = [elements]
"""
class_filter = ElementClassFilter(SharedParameterElement,True)

parameters = FilteredElementCollector(doc).OfClass(ParameterElement).WherePasses(class_filter).ToElements()
"""

parameters = FilteredElementCollector(doc).OfClass(ParameterElement).ToElements()

for elem in elements:
	for param in parameters:
		if param.Name == elem:
			todelete.append(param.Id)

TransactionManager.Instance.EnsureInTransaction(doc)

res = [doc.Delete(i) for i in todelete]
				

TransactionManager.Instance.TransactionTaskDone()


OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="471cfdb6-3392-4b30-8112-ad51837920d8" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="RemoveProjectParameters" x="-110.764106800492" y="233.10687626331" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="70430d84-967a-4f11-b4bd-46e4603cd1f5" />
      <Name value="RemoveProjectParameters" />
      <Description value="Remove a single or a list of  project parameter by a parameter name or a list of parameters names. " />
      <Inputs>
        <Input value="ParameterName" />
      </Inputs>
      <Outputs>
        <Output value="Ids" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>