<Workspace Version="1.3.2.2480" X="-549.655556278604" Y="-596.589307830463" zoom="0.884263587285155" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="661.952281843516" y="494.640735539064" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="3ca40edc-2633-4993-9d70-b25cc585dc1c" type="DSRevitNodesUI.Categories" nickname="Categories" x="424.741625013561" y="579.358827264048" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="62794757-1b7a-41ba-807c-a07ee6cecea3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="869.527932451986" y="350.918699127934" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="757be5b9-af63-4b0a-98c9-cf7c873717e7" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Name" x="894.971499942636" y="733.281284197668" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Element.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Categories guid="615a717e-4bfe-41e1-bf96-796539d37ccc" type="DSRevitNodesUI.Categories" nickname="Categories" x="521.477582066802" y="737.371128662492" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="216:GenericModel" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6432e56c-d704-4d99-96f1-a531dd437700" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1128" y="606" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="Flatten(x);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <PythonNodeModels.PythonNode guid="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1330.33525732522" y="757.316838680575" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
clr.AddReference("RevitNodes")

import System,Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from Autodesk.DesignScript.Geometry import *
from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elems = IN[0];

MassBICObj = System.Enum.ToObject(BuiltInCategory,BuiltInCategory.OST_Mass)

objId = ElementId(MassBICObj)
directShapeType = DirectShapeType.Create(doc,"ForRoom",objId)

if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

res = []
names = []

for e in elems:
	name = e.LookupParameter("Name").AsString()
	number = e.LookupParameter("Number").AsString()
	geoelem = e.GetGeometryObjectFromReference(Reference(e))
	geoobj = geoelem.GetEnumerator();
	for obj in geoobj:	
		res.append(obj.ToProtoType())
		names.append(number+"_"+name)
OUT = res,names,objId,directShapeType</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="334004d3-1e7d-48ac-8f99-5c7cc2c0f4f9" type="PythonNodeModels.PythonNode" nickname="BuiltInCategoryAndID" x="1188.69407848502" y="898.102178374459" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="true" inputcount="0">
      <Script>import clr,System
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

builtInCategories = System.Enum.GetValues(BuiltInCategory)
res = []
for bic in builtInCategories:
	try:
		res.append([builtInCategories,ElementId(bic)])
	except:
		pass
		
OUT = res</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" start_index="0" end="62794757-1b7a-41ba-807c-a07ee6cecea3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" start_index="0" end="757be5b9-af63-4b0a-98c9-cf7c873717e7" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" start_index="0" end="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ca40edc-2633-4993-9d70-b25cc585dc1c" start_index="0" end="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="62794757-1b7a-41ba-807c-a07ee6cecea3" start_index="0" end="6432e56c-d704-4d99-96f1-a531dd437700" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17812.087890625" eyeY="38503.35546875" eyeZ="23717.98046875" lookX="17807.087890625" lookY="-38492.35546875" lookZ="-23725.98046875" upX="0.385847300291061" upY="0.766044437885284" upZ="-0.51409900188446" />
  </Cameras>
</Workspace>