<Workspace Version="1.3.2.2480" X="89.5341339020772" Y="118.78021" zoom="0.70823125" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="677dc976-36f4-4e47-be84-4ce0c7bd1bcf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="484.8" y="188" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import System
from System import EventHandler
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import RevitCommandId
import Autodesk
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI import *
from Autodesk.Revit.UI.Events import DialogBoxShowingEventArgs
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication

def confirm(sender, eventArgs):
	return eventArgs.OverrideResult(TaskDialogResult.Ok)
	
bool = IN[0] 

if bool ==  True:

	CmndID = RevitCommandId.LookupCommandId('ID_PURGE_UNUSED')
	#cmdMonitor = RevitCommandEndedMonitor(uiapp)
	uiapp.PostCommand(CmndID)
	#dialogEventHandler = EventHandler[DialogBoxShowingEventArgs](confirm)
	uiapp.DialogBoxShowing += confirm
	#RevitCommandId.LookupPostableCommandId
	#uiapp.DialogBoxShowing -= dialogEventHandler
	
	error = 'Success'
else:
	error = 'Set IN[0] to true'

#Assign your output to the OUT variable
OUT = uiapp.DialogBoxShowing</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.BoolSelector guid="2c1a0e82-e225-452c-8f78-4f32c11c2444" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="107.2" y="285.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <PythonNodeModels.PythonNode guid="12e39742-079f-44e0-87b5-a76d47d6ee21" type="PythonNodeModels.PythonNode" nickname="Python Script" x="424.8" y="408.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
import System
from System import EventHandler
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.UI import RevitCommandId
import Autodesk
clr.AddReference('RevitServices')
import RevitServices
from RevitServices.Persistence import DocumentManager
clr.AddReference("RevitAPIUI")
from Autodesk.Revit.UI.Events import DialogBoxShowingEventArgs
doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication

	
bool = IN[0] 

if bool ==  True:

	CmndID = RevitCommandId.LookupCommandId('ID_PURGE_UNUSED')
	#cmdMonitor = RevitCommandEndedMonitor(uiapp)
	dialog = uiapp.PostCommand(CmndID)
	dialogEventHandler = EventHandler[DialogBoxShowingEventArgs](confirm)
	#uiapp.DialogBoxShowing += dialogEventHandler
	#RevitCommandId.LookupPostableCommandId
	#uiapp.DialogBoxShowing -= dialogEventHandler
	
	
	error = 'Success'
else:
	error = 'Set IN[0] to true'

#Assign your output to the OUT variable
OUT = CmndID.Name</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2c1a0e82-e225-452c-8f78-4f32c11c2444" start_index="0" end="677dc976-36f4-4e47-be84-4ce0c7bd1bcf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2c1a0e82-e225-452c-8f78-4f32c11c2444" start_index="0" end="12e39742-079f-44e0-87b5-a76d47d6ee21" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>