<Workspace Version="1.3.2.2480" X="50.6739999999999" Y="-49.43" zoom="0.8425" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="4afb4655-88f6-4467-a777-f015480ef7e5" type="PythonNodeModels.PythonNode" nickname="Python Script" x="148.517507418397" y="322.015430267062" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="0">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

# collect user created worksets
worksets = FilteredWorksetCollector(doc).OfKind(WorksetKind.UserWorkset).ToWorksets()

# return list structure [[name,workset],[]...[]]
OUT = [[i.Name,i] for i in worksets]</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="79fb00d9-7306-42e5-b0a0-6e5d1a5a6c49" annotationText="return [[name,workset],[]..[]]" left="138.517507418397" top="240.015430267062" width="285.396666666667" height="174.6" fontSize="30" InitialTop="322.015430267062" InitialHeight="122.6" TextblockHeight="72" backgrouund="#FFB9F9E1">
      <Models ModelGuid="4afb4655-88f6-4467-a777-f015480ef7e5" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>