<Workspace Version="1.3.2.2480" X="-118.327423568465" Y="45.7036854637584" zoom="0.397696046784057" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Categories guid="2718ca18-b38a-410d-a1dd-b5843c186e4b" type="DSRevitNodesUI.Categories" nickname="Categories" x="436.8" y="252" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="574:Walls" />
    <DSRevitNodesUI.ElementsOfCategory guid="22f95931-e9e6-436d-9df0-11094fb25be3" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="679.2" y="257.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="7d333efb-cdd7-442e-88fd-dbc75953f1e6" type="DSRevitNodesUI.Categories" nickname="Categories" x="466.158781108659" y="524.593006201434" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="331:PipeCurves" />
    <DSRevitNodesUI.ElementsOfCategory guid="8547be3b-2a1c-4183-b206-f42716a48e1c" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="708.558781108659" y="530.193006201434" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="04b28173-4d5a-4f80-a617-55b737dff4a3" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="950.901209344984" y="256.292370598365" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d1ee5a87-ab40-4ca7-9df4-3bb073288728" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Geometry" x="952.845330946406" y="536.428827434872" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="dc67a561-7217-41f3-ae96-4f4d4953b4af" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1185.96261499935" y="604.729695733733" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="4ba5c370-6095-4efc-bad7-d75d732588a8" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1208.54418977785" y="344.824376250306" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="03202a79-3bc0-4b84-9b48-1b1402bd949f" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1154.6469377656" y="-93.4772464496075" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

walls = IN[0]
pipes = IN[1]
intersections = []

for wall in walls:
	for pipe in pipes:
		intersect = Geometry.Intersect(wall, pipe)
		if intersect:
			intersections.append(intersect)

OUT = intersections</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5a84e236-15b5-467d-af3a-30bad320dab4" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Centroid" x="1575.04817036032" y="-97.5754483215153" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Centroid">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="47eb96e8-42d3-4a03-84ac-712909c5e6b0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Flatten" x="1326.75826314974" y="-90.2820049831813" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="BuiltIn" function="Flatten@var[]..[]">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.FamilyTypes guid="323437c1-35da-4b7a-98ba-2d707e117954" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="1561.59598108839" y="13.8256229993338" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="51:Family1:Family1" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ad5b6f76-00d3-4078-bf9f-44eac6e857cd" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="FamilyInstance.ByPoint" x="1958.85264878671" y="-93.1270772088413" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.ByPoint@Revit.Elements.FamilyType,Autodesk.DesignScript.Geometry.Point">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="28c1dd82-9800-4c8d-8016-1e40903dbe85" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1609.24788687708" y="360.278041670993" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

walls = IN[0]
pipes = IN[1]
intersections = []

for wall in walls:
	for pipe in pipes:
		intersect = Geometry.Intersect(wall, pipe)
		if intersect:
			intersections.append(intersect)
			

OUT = intersections</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="0129e25e-cac9-4be7-93d2-ed886b363f09" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1169.79015594997" y="733.294817429015" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitNodes')
clr.AddReference('RevitAPI')

import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

from Autodesk.DesignScript.Geometry import *
from Autodesk.Revit.DB import *

walls = UnwrapElement(IN[0])
pipes = UnwrapElement(IN[1])
intersections = []


def geo_con(e):
	# get geo-objects of the element
	geoelem = e.GetGeometryObjectFromReference(Reference(e))
	# get enumerator to loop geo-objects
	geoobj = geoelem.GetEnumerator()
	# loop geo-objector
	for obj in geoobj:
		# convert to dynamo type
		geo = obj.ToProtoType()
	# return geometry
	return geo


for wall in walls:
	intersections.append(geo_con(wall))


	

OUT = intersections</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="c6eb87db-5782-454f-941c-96cdd6affc06" type="PythonNodeModels.PythonNode" nickname="CenterRoom" x="1603.963140029" y="643.197303745636" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2
# author - min.naung/mgjean https://twentytwo.space/contact/

import clr
clr.AddReference('ProtoGeometry')
clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')
clr.AddReference("RevitNodes")

import System
import Revit
#clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)
from Autodesk.DesignScript.Geometry import (Geometry,
Point as pt)
from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elems = IN[0];

# make list
if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

# output
res = []
# start transaction
TransactionManager.Instance.EnsureInTransaction(doc)

# loop elements
for e in elems:
	# level elevation - unit millimeter 
	elevation = e.Level.Elevation * 304.8
	# get geo-objects of the element
	geoelem = e.GetGeometryObjectFromReference(Reference(e))
	# get enumerator to loop geo-objects
	geoobj = geoelem.GetEnumerator()
	# loop geo-objector
	for obj in geoobj:
		# convert to dynamo type
		room_geometry = obj.ToProtoType()
		# get the centroid of the element
		point = room_geometry.Centroid()
		# create location point with level elevation
		center = pt.ByCoordinates(point.X,point.Y,elevation)
		# current element location
		current = e.Location.Point
		# point convert to revit and minus from current location
		newloc = center.ToXyz() - current
		# move to new location
		e.Location.Move(newloc)

# transaction done
TransactionManager.Instance.TransactionTaskDone()

# output
OUT = elems




















</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2718ca18-b38a-410d-a1dd-b5843c186e4b" start_index="0" end="22f95931-e9e6-436d-9df0-11094fb25be3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22f95931-e9e6-436d-9df0-11094fb25be3" start_index="0" end="04b28173-4d5a-4f80-a617-55b737dff4a3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="22f95931-e9e6-436d-9df0-11094fb25be3" start_index="0" end="0129e25e-cac9-4be7-93d2-ed886b363f09" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7d333efb-cdd7-442e-88fd-dbc75953f1e6" start_index="0" end="8547be3b-2a1c-4183-b206-f42716a48e1c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8547be3b-2a1c-4183-b206-f42716a48e1c" start_index="0" end="d1ee5a87-ab40-4ca7-9df4-3bb073288728" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8547be3b-2a1c-4183-b206-f42716a48e1c" start_index="0" end="0129e25e-cac9-4be7-93d2-ed886b363f09" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="04b28173-4d5a-4f80-a617-55b737dff4a3" start_index="0" end="4ba5c370-6095-4efc-bad7-d75d732588a8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1ee5a87-ab40-4ca7-9df4-3bb073288728" start_index="0" end="dc67a561-7217-41f3-ae96-4f4d4953b4af" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc67a561-7217-41f3-ae96-4f4d4953b4af" start_index="0" end="03202a79-3bc0-4b84-9b48-1b1402bd949f" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dc67a561-7217-41f3-ae96-4f4d4953b4af" start_index="0" end="28c1dd82-9800-4c8d-8016-1e40903dbe85" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ba5c370-6095-4efc-bad7-d75d732588a8" start_index="0" end="03202a79-3bc0-4b84-9b48-1b1402bd949f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4ba5c370-6095-4efc-bad7-d75d732588a8" start_index="0" end="28c1dd82-9800-4c8d-8016-1e40903dbe85" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03202a79-3bc0-4b84-9b48-1b1402bd949f" start_index="0" end="47eb96e8-42d3-4a03-84ac-712909c5e6b0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5a84e236-15b5-467d-af3a-30bad320dab4" start_index="0" end="ad5b6f76-00d3-4078-bf9f-44eac6e857cd" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="47eb96e8-42d3-4a03-84ac-712909c5e6b0" start_index="0" end="5a84e236-15b5-467d-af3a-30bad320dab4" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="323437c1-35da-4b7a-98ba-2d707e117954" start_index="0" end="ad5b6f76-00d3-4078-bf9f-44eac6e857cd" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="7518e191-d540-4edd-a05f-09b1bb348f9c" annotationText="Place Dummy Family" left="1144.6469377656" top="-143.575448321515" width="1098.60571102111" height="250.001071320849" fontSize="30" InitialTop="-97.5754483215153" InitialHeight="234.001071320849" TextblockHeight="36" backgrouund="#FFA4E1FF">
      <Models ModelGuid="03202a79-3bc0-4b84-9b48-1b1402bd949f" />
      <Models ModelGuid="5a84e236-15b5-467d-af3a-30bad320dab4" />
      <Models ModelGuid="47eb96e8-42d3-4a03-84ac-712909c5e6b0" />
      <Models ModelGuid="323437c1-35da-4b7a-98ba-2d707e117954" />
      <Models ModelGuid="ad5b6f76-00d3-4078-bf9f-44eac6e857cd" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-14152.7086314476" eyeY="18055.5190739183" eyeZ="7502.78729672994" lookX="13140.8590220726" lookY="-18162.0276188402" lookZ="-8569.89264340963" upX="0.501752578757503" upY="0.800731363173167" upZ="-0.327221057179431" />
  </Cameras>
</Workspace>