<Workspace Version="1.3.2.2480" X="321.973743847742" Y="479.489200211785" zoom="0.766189997407438" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection guid="2c000785-6349-45dd-a97b-75eaadfd2f5a" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="-51.7040646075947" y="-522.067128963235" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="d9f04446-f80f-407d-b767-e990a62a7a3f-0005439f" />
    </Dynamo.Nodes.DSModelElementSelection>
    <PythonNodeModels.PythonNode guid="029c5f80-30b8-4087-ad41-8471a7b92832" type="PythonNodeModels.PythonNode" nickname="Python Script" x="23.3182339015779" y="-394.23245298913" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="0">
      <Script>import clr

clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Structure import *

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

TransactionManager.Instance.EnsureInTransaction(doc)

newtype = RebarCoverType.Create(doc,"NewType1", 20/304.8)

TransactionManager.Instance.TransactionTaskDone()


OUT = newtype
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="196d33fc-19f5-4c68-afce-34493ef5897b" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="181.251583505799" y="-275.354521219127" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="{&quot;Rebar Cover - Top Face&quot;,&#xA;&quot;Rebar Cover - Bottom Face&quot;,&#xA;&quot;Rebar Cover - Other Faces&quot;};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b4e7a81b-a2af-451e-a4cf-882eda2b1caf" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.SetParameterByName" x="262.677396174965" y="-546.233861262088" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.SetParameterByName@string,var">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.HigherOrder.Map guid="41f489fd-4391-4109-9f88-b89b9a2f478f" type="CoreNodeModels.HigherOrder.Map" nickname="List.Map" x="608.238501845696" y="-353.29252682457" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.HigherOrder.Map>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2c000785-6349-45dd-a97b-75eaadfd2f5a" start_index="0" end="b4e7a81b-a2af-451e-a4cf-882eda2b1caf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="029c5f80-30b8-4087-ad41-8471a7b92832" start_index="0" end="b4e7a81b-a2af-451e-a4cf-882eda2b1caf" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="196d33fc-19f5-4c68-afce-34493ef5897b" start_index="0" end="41f489fd-4391-4109-9f88-b89b9a2f478f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b4e7a81b-a2af-451e-a4cf-882eda2b1caf" start_index="0" end="41f489fd-4391-4109-9f88-b89b9a2f478f" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>