<Workspace Version="1.3.2.2480" X="-23.7732403039141" Y="8.71136428292544" zoom="0.687429564313341" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="6458dd9c-adff-46ca-9784-7427c736c919" type="PythonNodeModels.PythonNode" nickname="Python Script" x="461.611383078834" y="367.540483584002" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2

# import common language runtime 
import clr

# clr.AddReference loads and imports .net assembly(dll)
# load RevitAPI.dll and RevitServices.dll
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

# import all classes from Revit DB
from Autodesk.Revit.DB import *
# import document manager
from RevitServices.Persistence import DocumentManager
# import transaction manager
from RevitServices.Transactions import TransactionManager
# instantiate current document
doc = DocumentManager.Instance.CurrentDBDocument

# if provided input[0]
if IN[0]:
	rooms = UnwrapElement(IN[0])
	
# if no input, collect all rooms
else:
	# collect all rooms 
	rooms = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Rooms).ToElements()

# room status list for output
placed,notplaced,notenclosed,redundant = [],[],[],[]

# loop rooms
for r in rooms:
	# get room boundary need one argument(opts)
	s = r.GetBoundarySegments(SpatialElementBoundaryOptions())
	# get location of room
	l = r.Location
	# if location is none
	if l == None:
		# append to not placed
		notplaced.append(r)
	# elif no boundary segments
	elif len(s)&lt;1:
		# append to not enclosed
		notenclosed.append(r)
	# elif area zero
	elif r.Area == 0:
		# append to redundant
		redundant.append(r)
	# passed all conditions
	else:
		# append to placed
		placed.append(r)

OUT = placed,notplaced,notenclosed,redundant





</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Categories guid="bec1fa33-6db7-4fe8-b82c-4ea90dcd83ca" type="DSRevitNodesUI.Categories" nickname="Categories" x="-358.002940657647" y="274.469479568589" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <DSRevitNodesUI.ElementsOfCategory guid="27ce2083-beb1-4ac2-a346-40348ee155cb" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="-160.060688691906" y="292.658767587063" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="819180c6-1f87-48e7-a658-0ec255964fec" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-9.19644368539326" y="416.079965106945" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="i[2..4];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d39435fe-561b-454f-bef3-61732fbd4232" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.Name" x="666.263129560887" y="372.38462515604" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="RevitNodes.dll" function="Revit.Elements.Room.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6458dd9c-adff-46ca-9784-7427c736c919" start_index="0" end="d39435fe-561b-454f-bef3-61732fbd4232" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bec1fa33-6db7-4fe8-b82c-4ea90dcd83ca" start_index="0" end="27ce2083-beb1-4ac2-a346-40348ee155cb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="27ce2083-beb1-4ac2-a346-40348ee155cb" start_index="0" end="819180c6-1f87-48e7-a658-0ec255964fec" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="73722908-1f32-460e-b6b0-c0b6e53922cd" text="**NOTE&#xD;&#xA;IN[0] accepted; if not IN[0]; collect all rooms;" x="394.553721192481" y="212.790598879038" />
    <Dynamo.Graph.Notes.NoteModel guid="25f393e7-f6e4-465c-b35c-683ff450eebb" text="Returns;&#xD;&#xA;OUT[0] = Placed rooms;&#xD;&#xA;OUT[1] = Unplaced rooms;&#xD;&#xA;OUT[2] = Not Enclosed rooms;&#xD;&#xA;OUT[3] = Redundant rooms;" x="441.639216256922" y="271.123582549137" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="5fe20d84-f6c3-44aa-a671-9c6baec0945d" annotationText="RoomsCollector" left="384.553721192481" top="166.790598879038" width="283.412338113647" height="293.349884704964" fontSize="30" InitialTop="212.790598879038" InitialHeight="363.723841434873" TextblockHeight="36" backgrouund="#FFB9F9E1">
      <Models ModelGuid="6458dd9c-adff-46ca-9784-7427c736c919" />
      <Models ModelGuid="73722908-1f32-460e-b6b0-c0b6e53922cd" />
      <Models ModelGuid="25f393e7-f6e4-465c-b35c-683ff450eebb" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>