<Workspace Version="1.3.2.2480" X="-191.483105244665" Y="-211.067732920439" zoom="0.762603431411883" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="647.493532668721" y="529.724356113797" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="3ca40edc-2633-4993-9d70-b25cc585dc1c" type="DSRevitNodesUI.Categories" nickname="Categories" x="399.352529133932" y="547.134205570672" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <PythonNodeModels.PythonNode guid="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="881.842485139592" y="534.621469922429" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2'
# author - min.naung/mgjean @https://twentytwo.space/contact


import clr,System

clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

from System.Collections.Generic import List

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elems = IN[0];

MassBICObj = System.Enum.ToObject(BuiltInCategory,BuiltInCategory.OST_Mass)

objId = ElementId(MassBICObj)

if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

res = []

# transaction start
TransactionManager.Instance.EnsureInTransaction(doc)

for e in elems:
	name = e.LookupParameter("Name").AsString()
	number = e.LookupParameter("Number").AsString()
	# name
	elem_name = number+"_"+name
	# collect geometry element
	geoobj = e.Geometry[Options()]
	# make enum to get geometry object
	enum = geoobj.GetEnumerator();
	shape = [i for i in enum][0]
	
	# create direct shape type
	shapeType = DirectShapeType.Create(doc,elem_name,objId)
	# set shape to geometry list shape
	shapeType.SetShape([shape])
	# get dslibrary
	lib = DirectShapeLibrary.GetDirectShapeLibrary(doc)
	# add type to dslibrary
	lib.AddDefinitionType(elem_name,shapeType.Id)
	# create element by shapetype
	element = DirectShape.CreateElementInstance(doc,shapeType.Id,objId,elem_name,Transform.Identity)
	# set typeId
	element.SetTypeId(shapeType.Id)
	# append to output
	res.append(element)
# transaction end		
TransactionManager.Instance.TransactionTaskDone()

OUT = res




















</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="65337a0b-7c36-423c-9aa8-9ff0b736b42c" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Springs.DirectShape.ByGeometry" x="638.540181720041" y="622.784453605915" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="False" />
      <ID value="2416ec21-d9a2-4c67-a742-20d5cf82446e" />
      <Name value="Springs.DirectShape.ByGeometry" />
      <Description value="Convert the input geometry to DirectShape element inside the Revit document.  It supports solids or surfaces. It is based on an alternative process that uses a SAT import and can produce smooth surfaces. Each created DS will have a unique type. Make sure that each input geometry has a unique name. You can either feed a single category for all geometries or a unique category for each geometry - the node's lacing is set to longest by default. The default category is &#xD;&#xA;Generic Models." />
      <Inputs>
        <Input value="geometry" />
        <Input value="category" />
        <Input value="name" />
      </Inputs>
      <Outputs>
        <Output value="DirectShape" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" start_index="0" end="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ca40edc-2633-4993-9d70-b25cc585dc1c" start_index="0" end="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17812.087890625" eyeY="38503.35546875" eyeZ="23717.98046875" lookX="17807.087890625" lookY="-38492.35546875" lookZ="-23725.98046875" upX="0.385847300291061" upY="0.766044437885284" upZ="-0.51409900188446" />
  </Cameras>
</Workspace>