<Workspace Version="1.3.2.2480" X="76.5999460602263" Y="-313.47962416388" zoom="1.06353959856905" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="2961f0d4-bddc-488b-adb8-113b540193a0" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Circle.ByCenterPointRadius" x="-110.678233917904" y="22.0823497910205" isVisible="false" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="f666dcc6-8cf4-4cfb-9a20-f96aaca4ba35" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.Origin" x="-354.142777165586" y="112.271225714862" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Origin" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e2c9e35a-b6d0-4e0c-8484-0660c1e865e0" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="152.310053050671" y="453.002337286233" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="7;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="0741c44d-4bae-4f9c-ad6e-45ad67172a48" type="PythonNodeModels.PythonNode" nickname="Python Script" x="385.584050865808" y="455.120110898148" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

curve = IN[0]
side = float(IN[1])
times = IN[2]

base = float(1/side)
increment = 0
points = []
res = []
increment_list = []
x = times
toprint= []

for i in range(int(side)):
	increment += base
	increment_list.append(increment)
	point = Curve.PointAtParameter(curve,increment)
	points.append(point)

for num,point in enumerate(points):
	if num &lt; len(points)-x:
		next = num + x
		line = Line.ByStartPointEndPoint(point, points[next])
	for amt in range(x):
		if num &gt; len(points)-x and num % x == amt:
			line = Line.ByStartPointEndPoint(point, points[amt])	
		if num == len(points)-x and num % x == amt:
			line = Line.ByStartPointEndPoint(point,	points[amt])
	
	res.append(line);

OUT = res,points,toprint





</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="78901733-e629-4330-9004-075044d2bdd9" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="151.915088525478" y="535.268902448023" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="2;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="761313c9-192c-408b-a317-f66819c25c4d" type="PythonNodeModels.PythonNode" nickname="FollowSide" x="247.703264921871" y="-37.8472915107418" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr,sys
sys.path.append(r"C:\Program Files (x86)\IronPython 2.7\Lib")
import math
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

curve = IN[0]
x = int(IN[1])
side = float(x * x)

base = float(1/side)
increment = 0
points = []
res = []
increment_list = []


for i in range(int(side)):
	increment += base
	increment_list.append(increment)
	point = Curve.PointAtParameter(curve,increment)
	points.append(point)

for num,point in enumerate(points):
	if num &lt; len(points)-x:
		next = num + x
		line = Line.ByStartPointEndPoint(point, points[next])
	for amt in range(x):
		if num &gt;= len(points)-x and num % x == amt:
			line = Line.ByStartPointEndPoint(point, points[amt])	

	res.append(line);

OUT = res




</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.DoubleSlider guid="4595822a-cb47-4a5d-a67f-281f53c30d2c" type="CoreNodeModels.Input.DoubleSlider" nickname="Number Slider" x="32.5185157319151" y="193.700240931951" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double>3</System.Double>
      <Range min="1" max="20" step="1" />
    </CoreNodeModels.Input.DoubleSlider>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="596740c7-0741-4d5f-aacd-02c209e65f5d" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-241.973427326133" y="179.048140962601" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="2;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2961f0d4-bddc-488b-adb8-113b540193a0" start_index="0" end="0741c44d-4bae-4f9c-ad6e-45ad67172a48" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2961f0d4-bddc-488b-adb8-113b540193a0" start_index="0" end="761313c9-192c-408b-a317-f66819c25c4d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f666dcc6-8cf4-4cfb-9a20-f96aaca4ba35" start_index="0" end="2961f0d4-bddc-488b-adb8-113b540193a0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e2c9e35a-b6d0-4e0c-8484-0660c1e865e0" start_index="0" end="0741c44d-4bae-4f9c-ad6e-45ad67172a48" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="78901733-e629-4330-9004-075044d2bdd9" start_index="0" end="0741c44d-4bae-4f9c-ad6e-45ad67172a48" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="4595822a-cb47-4a5d-a67f-281f53c30d2c" start_index="0" end="761313c9-192c-408b-a317-f66819c25c4d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="596740c7-0741-4d5f-aacd-02c209e65f5d" start_index="0" end="2961f0d4-bddc-488b-adb8-113b540193a0" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.593605220317841" eyeY="4.88046503067017" eyeZ="1.67942333221436" lookX="-0.000223018840188161" lookY="-0.00891566555947065" lookZ="-0.00201664841733873" upX="-0.0994574427604675" upY="0.425779283046722" upZ="-0.899344325065613" />
  </Cameras>
</Workspace>