<Workspace Version="1.3.2.2480" X="225.6" Y="137.6" zoom="1" ScaleFactor="1" Name="SetFillRegionLine" Description="Modify fill region type line styles by given line style type in active view (default), set false to modify all view in the document. " ID="8834f6e5-f2c7-4df2-85ec-3cc5b4549004" Category="Quasar.LineUtility">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="b6a870de-5091-431e-9d05-359043253e16" type="PythonNodeModels.PythonNode" nickname="FillRegions" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>
import clr


clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

frtId = UnwrapElement(IN[0]).Id
lineId = UnwrapElement(IN[1]).Id
active_view = IN[2]

if active_view:
	elems = FilteredElementCollector(doc, doc.ActiveView.Id).OfClass(FilledRegion)
else:
	elems = FilteredElementCollector(doc).OfClass(FilledRegion)


res = []

TransactionManager.Instance.EnsureInTransaction(doc)

for i in elems:
		if frtId == i.GetTypeId():
			i.SetLineStyleId(lineId)
			res.append(i)
	
TransactionManager.Instance.TransactionTaskDone()


OUT = res

</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="4bf75b7a-e970-48eb-8435-3d33590f7778" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//fill region elements&#xD;&#xA;FillRegionElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="df45d166-1ddc-4921-b694-570c02ba859c" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-22.4" y="-0.800000000000011" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// fill region type&#xD;&#xA;FillRegionType;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="b1cd9505-a2ac-4c1b-8fc1-64e6f6cf5c5a" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="4.80000000000007" y="73.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// line styles type&#xD;&#xA;LineStyleType;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="5b57fd62-0838-47a6-b6e9-3ad864d826dd" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-32.7999999999998" y="153.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// boolean value for active view&#xD;&#xA;ActiveViewOnly = true" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="b6a870de-5091-431e-9d05-359043253e16" start_index="0" end="4bf75b7a-e970-48eb-8435-3d33590f7778" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="df45d166-1ddc-4921-b694-570c02ba859c" start_index="0" end="b6a870de-5091-431e-9d05-359043253e16" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b1cd9505-a2ac-4c1b-8fc1-64e6f6cf5c5a" start_index="0" end="b6a870de-5091-431e-9d05-359043253e16" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="5b57fd62-0838-47a6-b6e9-3ad864d826dd" start_index="0" end="b6a870de-5091-431e-9d05-359043253e16" end_index="2" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="a7d35e60-4238-49fc-b121-3cfadb314b9e" text="** Change Fill Region Line Style (Active View Only)&#xD;&#xA;IN[0] = Fill Region Type&#xD;&#xA;IN[1] = Line Style&#xD;&#xA;IN[2] = Active view (boolean)" x="198.440599817133" y="-84.0837711372956" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-873.067626953125" eyeY="8069.2265625" eyeZ="1481.33715820313" lookX="413.761810302734" lookY="-7718.25244140625" lookZ="-1999.84875488281" upX="0.180200740695" upY="0.457097917795181" upZ="-0.870970249176025" />
  </Cameras>
</Workspace>