<Workspace Version="1.3.4.6666" X="150.543193833948" Y="-105.211709509983" zoom="0.632527700865846" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a0ec2353-2cb4-4d96-bec2-5eefc304b123" type="PythonNodeModels.PythonNode" nickname="Python Script" x="308.053153070188" y="482.541529784137" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.4

import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager

# the current document
doc = DocumentManager.Instance.CurrentDBDocument

# output lists
names, owners = [], []

# input filepath
file_path = IN[0]
# convert filepath to modelpath
model_path = ModelPathUtils.ConvertUserVisiblePathToModelPath(file_path)
# collect workset info
worksets = WorksharingUtils.GetUserWorksetInfo(model_path);
# each workset
for workset in worksets:
	# workset name
	names.append(workset.Name)
	# workset owner
	owners.append(workset.Owner)

# output results
OUT = names, owners
	</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.Filename guid="5c540d9b-8231-4e3e-8cd7-921aa34aa004" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-258.996466651364" y="470.656719333641" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>\\SpecialistSvr\02_Shared\MinNaung\Element_Info.rvt</System.String>
      <HintPath>\\SpecialistSvr\02_Shared\MinNaung\Element_Info.rvt</HintPath>
    </CoreNodeModels.Input.Filename>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="5c540d9b-8231-4e3e-8cd7-921aa34aa004" start_index="0" end="a0ec2353-2cb4-4d96-bec2-5eefc304b123" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-23.6224803924561" eyeY="357.151702880859" eyeZ="235.368255615234" lookX="61.4809913635254" lookY="-66.6044082641602" lookZ="-297.158111572266" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>