<Workspace Version="1.3.4.6666" X="-68.106786997132" Y="264.687420059092" zoom="0.888789228297156" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Directory" resolvedName="DSCore.IO.Directory" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Strings" resolvedName="Lists.Strings" assemblyName="LunchBox.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <CoreNodeModels.Input.Directory guid="9de238c2-6881-4825-9cb2-d6389bf1b94f" type="CoreNodeModels.Input.Directory" nickname="Directory Path" x="136.441038799055" y="-99.8289342951904" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>C:\Users\mrmin\OneDrive\Desktop\fads</System.String>
      <HintPath>C:\Users\mrmin\OneDrive\Desktop\fads</HintPath>
    </CoreNodeModels.Input.Directory>
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="c3fb1eba-6460-44c7-8fb7-8feede09af39" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="ExportRevitLinks" x="433.695660540455" y="-110.031889981771" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true">
      <PortInfo index="0" default="False" />
      <ID value="6e24ceed-ac89-4a9b-a1d0-3b0b6825bc7a" />
      <Name value="ExportRevitLinks" />
      <Description value="Export all loaded revit link documents to a given directory." />
      <Inputs>
        <Input value="OutputDirectory" />
      </Inputs>
      <Outputs>
        <Output value="FilePaths" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <PythonNodeModels.PythonNode guid="3d6426ac-27eb-4d9f-ae4a-02f7ae90b805" type="PythonNodeModels.PythonNode" nickname="Python Script" x="348.398385317379" y="145.514431225928" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.4 
# author - min.naung https://twentytwo.space

import clr,sys
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager

pyt_path = r'C:\Program Files (x86)\IronPython 2.7\Lib';
sys.path.append(pyt_path);

import shutil,os

doc = DocumentManager.Instance.CurrentDBDocument;
link_docs = FilteredElementCollector(doc).OfClass(RevitLinkInstance);


# the current document path
# if the current document haven't created it returns ""
docPath = doc.PathName 
docName = os.path.basename(docPath).split(".")[0]
dirName = os.path.dirname(docPath)

if docName == "":
	docName = "TheCurrentDocument"

if dirName == "":	
	# make dir in the current user desktop
	dirName = os.path.join(os.path.join(os.environ["USERPROFILE"]),"Desktop")

# destination folder
folder = docName + "_LinkFileExport"
destFolder = os.path.join(dirName,folder)

# if folder does not exit
if not os.path.exists(destFolder):
	# create destination folder
	os.mkdir(destFolder)

# collect filepaths 
filepaths = []
for i in link_docs:
	# get link documents
	ldoc = i.GetLinkDocument()
	# if link is loaded
	if ldoc:
		# link file path
		lpath = ldoc.PathName
		# check if collected
		if lpath not in filepaths:
			filepaths.append(lpath);

# user input path
if IN[0] != None and os.path.exists(IN[0]):
	destFolder = IN[0]
			
# new filepaths and remove existing (override)
newfiles = []
for path in filepaths:
	newpath = os.path.join(destFolder, os.path.basename(path))
	newfiles.append(newpath)
	if os.path.exists(newpath):
		os.remove(newpath)

# copy files
output = []
for path in filepaths:
	# copy file 
	shutil.copy(path, destFolder);

OUT = newfiles


</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9de238c2-6881-4825-9cb2-d6389bf1b94f" start_index="0" end="c3fb1eba-6460-44c7-8fb7-8feede09af39" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>