<Workspace Version="1.3.4.6666" X="-567.463738801377" Y="-219.332970919181" zoom="0.611117808239932" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.FamilyTypes guid="9811dfd9-22ac-4163-a9e8-be971fcd65a5" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="1095.50533469408" y="404.363796448407" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="2:A2 metric:A2 metric" />
    <DSRevitNodesUI.Views guid="055078e3-7b73-486d-927f-2122933c268b" type="DSRevitNodesUI.Views" nickname="Views" x="1127.73508757444" y="617.14533530371" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="1:Level 1" />
    <CoreNodeModels.CreateList guid="ff837d9d-d0b4-418a-b799-11716c69ebea" type="CoreNodeModels.CreateList" nickname="List.Create" x="1415.14955761717" y="809.226419858646" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="6">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <PortInfo index="4" default="False" />
      <PortInfo index="5" default="False" />
    </CoreNodeModels.CreateList>
    <DSRevitNodesUI.Views guid="6da6d0b4-d7f8-4325-80eb-cf49c703b7bc" type="DSRevitNodesUI.Views" nickname="Views" x="1138.95542647162" y="688.626410232924" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="2:CLevel 1" />
    <DSRevitNodesUI.Views guid="ce9dfd83-f7e6-47ea-8190-53565c54f202" type="DSRevitNodesUI.Views" nickname="Views" x="1142.81260696181" y="869.214253279182" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="4:CLevel 2" />
    <DSRevitNodesUI.Views guid="9d1e6998-6aaf-4de8-b74b-e97ef8bb7b63" type="DSRevitNodesUI.Views" nickname="Views" x="1136.91259196667" y="774.804469559535" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="3:Level 2" />
    <PythonNodeModels.PythonNode guid="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1663.58156394892" y="855.921051232406" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")
clr.AddReference("RevitNodes")
import RevitServices
import Revit
import Autodesk
from Autodesk.Revit.DB import *

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
t = UnwrapElement(IN[0])
views = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)

sheet = ViewSheet.Create(doc, t.Id)

o = sheet.Outline

# role divider
b1 = 1.4
b2 = 3.5

# column divider
a2 = [2,4] # two column
a3 = [1.4,2.5,7] # three column

# first role
x = o.Max.U - o.Min.U
y = o.Max.V - o.Min.V

uv1 = XYZ( x/7, y/1.4, 0)
uv2 = XYZ( x/2.5, y/1.4, 0)
uv3 = XYZ( x/1.4, y/1.4, 0)

# second role
uv4 = XYZ( x/7, y/3.5,0)
uv5 = XYZ( x/2.5, y/3.5,0)
uv6 = XYZ( x/1.4, y/3.5,0)

for v,loc in zip(views,[uv1,uv2,uv3,uv4,uv5,uv6]):
	Viewport.Create(doc, sheet.Id , v.Id,loc)

TransactionManager.Instance.TransactionTaskDone()	

OUT = sheet</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Views guid="7f5f351f-2581-4e84-97fa-f244177543b6" type="DSRevitNodesUI.Views" nickname="Views" x="1158.66934573365" y="1069.26816631815" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="7:South" />
    <DSRevitNodesUI.Views guid="06c58fd6-eb48-41bc-8487-106e78509f3b" type="DSRevitNodesUI.Views" nickname="Views" x="1158.4789393598" y="966.8649305287" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="6:East" />
    <PythonNodeModels.PythonNode guid="a8f203ef-26c5-4444-ae26-49b98083d4d8" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2110.00994100146" y="329.884849609531" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
start = IN[0]
end = IN[1]
step = IN[2]

def irange(start,end,step):
	
	res = [start]
	if step == 1:
		return res
	if step == 2:
		res.append(end)
		return res
	if step &gt; 2:
		a = (end-start)/(step-1)
		t = step - 2
		ans = start
		for i in range(t):
			ans+=a
			res.append(ans)
		res.append(end)
		return res

a=irange(start,end,step)

OUT = a			</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="e550c244-b452-483a-b9be-4e71f8f164a5" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1964.31743419354" y="343.997254246871" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="1.4;&#xA;6;&#xA;5;" ShouldFocus="false" />
    <PythonNodeModels.PythonNode guid="5704707f-0114-46da-ac17-995f3281debc" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1657.8377592037" y="646.832652707068" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># dynamo version - 1.3.4

import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

t = UnwrapElement(IN[0])
views = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)

sheet = ViewSheet.Create(doc, t.Id)

o = sheet.Outline

# net values
x = o.Max.U - o.Min.U
y = o.Max.V - o.Min.V

uv1 = XYZ( x/5, y/1.4, 0)
uv2 = XYZ( x/1.7, y/1.4, 0)

# second role
uv3 = XYZ( x/5, y/3.5,0)
uv4 = XYZ( x/1.7, y/3.5,0)


for v,loc in zip(views,[uv1,uv2,uv3,uv4]):
	Viewport.Create(doc, sheet.Id , v.Id,loc)

TransactionManager.Instance.TransactionTaskDone()	

OUT = sheet</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9811dfd9-22ac-4163-a9e8-be971fcd65a5" start_index="0" end="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9811dfd9-22ac-4163-a9e8-be971fcd65a5" start_index="0" end="5704707f-0114-46da-ac17-995f3281debc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="055078e3-7b73-486d-927f-2122933c268b" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff837d9d-d0b4-418a-b799-11716c69ebea" start_index="0" end="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff837d9d-d0b4-418a-b799-11716c69ebea" start_index="0" end="5704707f-0114-46da-ac17-995f3281debc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6da6d0b4-d7f8-4325-80eb-cf49c703b7bc" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ce9dfd83-f7e6-47ea-8190-53565c54f202" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d1e6998-6aaf-4de8-b74b-e97ef8bb7b63" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7f5f351f-2581-4e84-97fa-f244177543b6" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="5" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="06c58fd6-eb48-41bc-8487-106e78509f3b" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="4" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e550c244-b452-483a-b9be-4e71f8f164a5" start_index="0" end="a8f203ef-26c5-4444-ae26-49b98083d4d8" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e550c244-b452-483a-b9be-4e71f8f164a5" start_index="1" end="a8f203ef-26c5-4444-ae26-49b98083d4d8" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e550c244-b452-483a-b9be-4e71f8f164a5" start_index="2" end="a8f203ef-26c5-4444-ae26-49b98083d4d8" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-265.807403564453" eyeY="493.266296386719" eyeZ="139.771743774414" lookX="58.6453475952148" lookY="-63.5324592590332" lookZ="-283.452514648438" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>