<Workspace Version="1.3.3.4651" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="7a062380-6e0a-4eda-91e9-23ffc6964ba7" type="PythonNodeModels.PythonNode" nickname="Python Script" x="239.2" y="268" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr,sys
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# add ipy library path
sys.path.append("C:\Program Files (x86)\IronPython 2.7\Lib")
# os module import
import os
# user desktop path
desktopPath = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')
# current document
doc = DocumentManager.Instance.CurrentDBDocument
# transaction start
TransactionManager.Instance.EnsureInTransaction(doc)

# image export options constructor
ieo = ImageExportOptions()
# export range (exporting amount of view(s))  
ieo.ExportRange = ExportRange.CurrentView
# file path
filePath = os.path.join(desktopPath, currentView.Name)
ieo.FilePath = filePath
# File type for exported HLR and wireframe views
ieo.HLRandWFViewsFileType = ImageFileType.PNG
# image resolution
ieo.ImageResolution = ImageResolution.DPI_300
# fit direction
ieo.FitDirection = FitDirectionType.Horizontal
# pixelsize
ieo.PixelSize = 1200
# file type for exported shadow views
ieo.ShadowViewsFileType = ImageFileType.PNG
# zoom type
ieo.ZoomType = ZoomFitType.FitToPage

# export image
doc.ExportImage(ieo)

TransactionManager.Instance.TransactionTaskDone()

OUT = ieo.FilePath







</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>