<Workspace Version="1.3.3.4651" X="404.218327222058" Y="-244.716556990991" zoom="0.729950825270786" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="fcb66e85-7b16-4135-a75e-ab772f8d4ea3" type="PythonNodeModels.PythonNode" nickname="Python Script" x="86.1695503642384" y="598.856449658286" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#TransactionManager.Instance.EnsureInTransaction()

pmgr = UnwrapElement(IN[0])
res = []

currentPrintSetting = pmgr.PrintSetup.CurrentPrintSetting
settingParams = currentPrintSetting.PrintParameters


for i in settingParams:
	if not i.startswith("__"):
		try:
			res.append([i, getattr(settingParams,i)])
		except:
			res.append(i + " can't get value.")

OUT = res</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" type="PythonNodeModels.PythonNode" nickname="Print Parameters" x="-222.210798360259" y="602.706404730698" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

sheet = UnwrapElement(IN[0])

pmgr = doc.PrintManager
res = []


# set in session
pmgr.PrintSetup.CurrentPrintSetting = pmgr.PrintSetup.InSession


# determine print range
pmgr.PrintRange = PrintRange.Select
# set printer
pmgr.SelectNewPrintDriver("PDF reDirect v2")
pmgr.PrintToFile = True
pmgr.PrintToFileName = IN[1]

currentPrintSetting = pmgr.PrintSetup.CurrentPrintSetting
settingParams = currentPrintSetting.PrintParameters


# color depth type enum
settingParams.ColorDepth = ColorDepthType.Color

# hidden line views type
settingParams.HiddenLineViews = HiddenLineViewsType.RasterProcessing

# hide crop boundaries
settingParams.HideCropBoundaries = False

# hide ref/work planes
settingParams.HideReforWorkPlanes = True

# hide scope boxes
settingParams.HideScopeBoxes = True

# hide unreferenced view tags
settingParams.HideUnreferencedViewTags = False

# paper placement
settingParams.PaperPlacement = PaperPlacementType.Margins

# margin type
settingParams.MarginType = MarginType.PrinterLimit

# mask coincident lines
settingParams.MaskCoincidentLines = False

# page orientation
settingParams.PageOrientation = PageOrientationType.Landscape

# paper size
A1 = [i for i in pmgr.PaperSizes if i.Name =="A1"][0]
settingParams.PaperSize = A1

# raseter quality type
settingParams.RasterQuality = RasterQualityType.Presentation

# replace halftone 
settingParams.ReplaceHalftoneWithThinLines = False

# zoom
settingParams.ZoomType = ZoomType.Zoom
settingParams.Zoom = 100

TransactionManager.Instance.EnsureInTransaction(doc)

pmgr.PrintSetup.CurrentPrintSetting = currentPrintSetting

pmgr.PrintSetup.SaveAs(IN[2])


TransactionManager.Instance.TransactionTaskDone()
pmgr.Apply()

# sheet
pmgr.SubmitPrint(sheet)

OUT = pmgr
</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.Views guid="ace7497f-2c95-46cd-8e8d-4a55890608f1" type="DSRevitNodesUI.Views" nickname="Views" x="-601.983465199932" y="528.140449526826" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="22:What's New in Templates and Content" />
    <CoreNodeModels.Input.Filename guid="6130d553-c520-4025-b018-755dfe7ac3e9" type="CoreNodeModels.Input.Filename" nickname="File Path" x="-409.093759310815" y="627.873195185404" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>.\efg.pdf</System.String>
      <HintPath>C:\Users\min.naung\Desktop\efg.pdf</HintPath>
    </CoreNodeModels.Input.Filename>
    <CoreNodeModels.Input.StringInput guid="0f5517c9-7fa3-48a3-aa20-c32f16e3a497" type="CoreNodeModels.Input.StringInput" nickname="String" x="-400.326045406764" y="735.277690510026" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>bbb</System.String>
      <System.String value="bbb" />
    </CoreNodeModels.Input.StringInput>
    <PythonNodeModels.PythonNode guid="0cebac4d-c77b-4077-a4f1-53788efc3530" type="PythonNodeModels.PythonNode" nickname="Python Script" x="136.716625895693" y="726.260944982908" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

#TransactionManager.Instance.EnsureInTransaction()

pmgr = UnwrapElement(IN[0])
res = []

currentPrintSetting = pmgr.PrintSetup.CurrentPrintSetting
settingParams = currentPrintSetting.PrintParameters


for i in settingParams:
	if not i.startswith("__"):
		try:
			res.append([i, getattr(settingParams,i)])
		except:
			res.append(i + " can't get value.")

OUT = res</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" start_index="0" end="fcb66e85-7b16-4135-a75e-ab772f8d4ea3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" start_index="0" end="0cebac4d-c77b-4077-a4f1-53788efc3530" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ace7497f-2c95-46cd-8e8d-4a55890608f1" start_index="0" end="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6130d553-c520-4025-b018-755dfe7ac3e9" start_index="0" end="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0f5517c9-7fa3-48a3-aa20-c32f16e3a497" start_index="0" end="aa0e2391-7d0f-4e85-82a2-2a96f5536bde" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>