<Workspace Version="1.3.4.6666" X="-401.55233740972" Y="-506.150501140585" zoom="1.39578138667476" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.ElementsOfCategory guid="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="623.69524045995" y="549.416619353275" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <DSRevitNodesUI.Categories guid="3ca40edc-2633-4993-9d70-b25cc585dc1c" type="DSRevitNodesUI.Categories" nickname="Categories" x="406.771263742545" y="550.156990198647" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="425:Rooms" />
    <PythonNodeModels.PythonNode guid="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" type="PythonNodeModels.PythonNode" nickname="Python Script" x="860.390412750855" y="547.075953309248" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr, System

clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# current document
doc = DocumentManager.Instance.CurrentDBDocument

# input
elems = IN[0];

# get mass category object
MassBICObj = System.Enum.ToObject(BuiltInCategory,BuiltInCategory.OST_Mass)

# mass object id
objId = ElementId(MassBICObj)

# make list
if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

# output result
res = []

# transaction start
TransactionManager.Instance.EnsureInTransaction(doc)

# each room
for e in elems:
	# get room name
	name = e.LookupParameter("Name").AsString()
	# get room number
	number = e.LookupParameter("Number").AsString()
	elem_name = number+"_"+name
	# collect geometry element
	geoobj = e.Geometry[Options()]
	# make enum to get geometry object
	enum = geoobj.GetEnumerator();
	shape = [i for i in enum][0]
	
	# create direct shape type
	shapeType = DirectShapeType.Create(doc,elem_name,objId)
	# set shape to geometry list shape
	shapeType.SetShape([shape])
	# get dslibrary
	lib = DirectShapeLibrary.GetDirectShapeLibrary(doc)
	# add type to dslibrary
	lib.AddDefinitionType(elem_name,shapeType.Id)
	# create element by shapetype
	element = DirectShape.CreateElementInstance(doc,shapeType.Id,objId,elem_name,Transform.Identity)
	# set typeId
	element.SetTypeId(shapeType.Id)
	# append to output
	res.append(element)
# transaction end		
TransactionManager.Instance.TransactionTaskDone()

OUT = res




















</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" start_index="0" end="7a5dbd2b-cf5e-492d-bf23-c6b466945b2c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ca40edc-2633-4993-9d70-b25cc585dc1c" start_index="0" end="21ea2004-56a5-4d8c-aaef-e0969edc5f3e" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="cdbd39ab-8310-45f9-b817-d90301fb2ab3" text="MassingByRoomScript" x="852.696877461966" y="513.265893037725" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17812.087890625" eyeY="38503.35546875" eyeZ="23717.98046875" lookX="17807.087890625" lookY="-38492.35546875" lookZ="-23725.98046875" upX="0.385847300291061" upY="0.766044437885284" upZ="-0.51409900188446" />
  </Cameras>
</Workspace>