<Workspace Version="1.3.4.6666" X="-776.740979418707" Y="-318.95172668364" zoom="0.713270132042073" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="087f66cf-bd7d-4217-ad1d-c426fefa4ccc" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ViewUtility.FloorPlanViewByRoom" x="757.491562119774" y="285.92763589442" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="true" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Quasar\bin\Quasar.dll" function="Quasar.ViewUtility.FloorPlanViewByRoom@Revit.Elements.Element,Revit.Elements.Room[],string[],double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="12e3d55b-ad31-4432-9288-4e612c387b61" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="ViewUtility.CeilingViewByRoom" x="762.251461832922" y="536.855555635326" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="true" isPinned="true" assembly="..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Quasar\bin\Quasar.dll" function="Quasar.ViewUtility.CeilingViewByRoom@Revit.Elements.Element,Revit.Elements.Room[],string[],double">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.Levels guid="e087fd17-5a71-4b5a-99b0-c49cd9402849" type="DSRevitNodesUI.Levels" nickname="Levels" x="169.07447539094" y="288.094446653932" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:Level 1" />
    <DSRevitNodesUI.Categories guid="391daedf-70b1-49b9-aa80-0d3458faaa30" type="DSRevitNodesUI.Categories" nickname="Categories" x="150.217508958685" y="402.686781126866" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="403:Rooms" />
    <DSRevitNodesUI.ElementsOfCategory guid="ae0a1520-ad72-4a82-89eb-17f8ffda7ebb" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="351.841996195872" y="402.686781126866" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="60577a2d-6038-4157-96e6-bc0395621bc6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Room.Name" x="467.853213849034" y="533.598861467082" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Room.Name">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="4e0e8120-b484-40fb-97b4-65da751a4723" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1732.84175920272" y="614.179756477335" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")
clr.AddReference("RevitNodes")
import RevitServices
import Revit
import Autodesk
from Autodesk.Revit.DB import *

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
t = UnwrapElement(IN[0])
views = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)

sheet = ViewSheet.Create(doc, t.Id)

o = sheet.Outline
uv1 = XYZ((o.Max.U-o.Min.U)/4, (o.Max.V - o.Min.V)/1.5,0)
uv2 = XYZ((o.Max.U-o.Min.U)/1.5, (o.Max.V - o.Min.V)/1.5,0)
uv3 = XYZ((o.Max.U-o.Min.U)/4, (o.Max.V - o.Min.V)/4,0)
uv4 = XYZ((o.Max.U-o.Min.U)/1.5, (o.Max.V - o.Min.V)/4,0)

for v,loc in zip(views,[uv1,uv2,uv3,uv4]):
	Viewport.Create(doc, sheet.Id , v.Id,loc)

TransactionManager.Instance.TransactionTaskDone()	

OUT = sheet</Script>
    </PythonNodeModels.PythonNode>
    <DSRevitNodesUI.FamilyTypes guid="9811dfd9-22ac-4163-a9e8-be971fcd65a5" type="DSRevitNodesUI.FamilyTypes" nickname="Family Types" x="1095.50533469408" y="404.363796448407" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:A1 metric:A1 metric" />
    <DSRevitNodesUI.Views guid="055078e3-7b73-486d-927f-2122933c268b" type="DSRevitNodesUI.Views" nickname="Views" x="1139.14836416268" y="554.752756621313" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="1:Level 1" />
    <CoreNodeModels.CreateList guid="ff837d9d-d0b4-418a-b799-11716c69ebea" type="CoreNodeModels.CreateList" nickname="List.Create" x="1406.32033135364" y="671.134741578391" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
    </CoreNodeModels.CreateList>
    <DSRevitNodesUI.Views guid="6da6d0b4-d7f8-4325-80eb-cf49c703b7bc" type="DSRevitNodesUI.Views" nickname="Views" x="1138.95542647162" y="688.626410232924" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="2:CLevel 1" />
    <DSRevitNodesUI.Views guid="ce9dfd83-f7e6-47ea-8190-53565c54f202" type="DSRevitNodesUI.Views" nickname="Views" x="1137.10299834052" y="969.703365013852" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="4:CLevel 2" />
    <DSRevitNodesUI.Views guid="9d1e6998-6aaf-4de8-b74b-e97ef8bb7b63" type="DSRevitNodesUI.Views" nickname="Views" x="1138.05451369093" y="827.332868875385" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="3:Level 2" />
    <CoreNodeModels.CreateList guid="1aa3923b-3a38-4ed6-9f07-6d7fd3bf6ae3" type="CoreNodeModels.CreateList" nickname="List.Create" x="1430.23709459315" y="924.502106292173" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </CoreNodeModels.CreateList>
    <PythonNodeModels.PythonNode guid="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1759.20664070793" y="806.714748152148" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('RevitAPI')
clr.AddReference("RevitServices")
clr.AddReference("RevitNodes")
import RevitServices
import Revit
import Autodesk
from Autodesk.Revit.DB import *

from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
t = UnwrapElement(IN[0])
views = UnwrapElement(IN[1])

TransactionManager.Instance.EnsureInTransaction(doc)

sheet = ViewSheet.Create(doc, t.Id)

o = sheet.Outline
uv1 = XYZ((o.Max.U-o.Min.U)/1, (o.Max.V - o.Min.V)/1,0)
uv2 = XYZ((o.Max.U-o.Min.U)/1.5, (o.Max.V - o.Min.V)/1,0)
uv3 = XYZ((o.Max.U-o.Min.U)/2, (o.Max.V - o.Min.V)/1,0)
uv4 = XYZ((o.Max.U-o.Min.U)/3, (o.Max.V - o.Min.V)/1,0)

for v,loc in zip(views,[uv1,uv2,uv3,uv4]):
	Viewport.Create(doc, sheet.Id , v.Id,loc)

TransactionManager.Instance.TransactionTaskDone()	

OUT = sheet</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="e087fd17-5a71-4b5a-99b0-c49cd9402849" start_index="0" end="087f66cf-bd7d-4217-ad1d-c426fefa4ccc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e087fd17-5a71-4b5a-99b0-c49cd9402849" start_index="0" end="12e3d55b-ad31-4432-9288-4e612c387b61" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="391daedf-70b1-49b9-aa80-0d3458faaa30" start_index="0" end="ae0a1520-ad72-4a82-89eb-17f8ffda7ebb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae0a1520-ad72-4a82-89eb-17f8ffda7ebb" start_index="0" end="087f66cf-bd7d-4217-ad1d-c426fefa4ccc" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae0a1520-ad72-4a82-89eb-17f8ffda7ebb" start_index="0" end="60577a2d-6038-4157-96e6-bc0395621bc6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ae0a1520-ad72-4a82-89eb-17f8ffda7ebb" start_index="0" end="12e3d55b-ad31-4432-9288-4e612c387b61" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="60577a2d-6038-4157-96e6-bc0395621bc6" start_index="0" end="087f66cf-bd7d-4217-ad1d-c426fefa4ccc" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="60577a2d-6038-4157-96e6-bc0395621bc6" start_index="0" end="12e3d55b-ad31-4432-9288-4e612c387b61" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9811dfd9-22ac-4163-a9e8-be971fcd65a5" start_index="0" end="4e0e8120-b484-40fb-97b4-65da751a4723" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9811dfd9-22ac-4163-a9e8-be971fcd65a5" start_index="0" end="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="055078e3-7b73-486d-927f-2122933c268b" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff837d9d-d0b4-418a-b799-11716c69ebea" start_index="0" end="4e0e8120-b484-40fb-97b4-65da751a4723" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ff837d9d-d0b4-418a-b799-11716c69ebea" start_index="0" end="eb6dad2b-60e6-40a8-ab75-e6377a0c4047" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6da6d0b4-d7f8-4325-80eb-cf49c703b7bc" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ce9dfd83-f7e6-47ea-8190-53565c54f202" start_index="0" end="1aa3923b-3a38-4ed6-9f07-6d7fd3bf6ae3" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ce9dfd83-f7e6-47ea-8190-53565c54f202" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="3" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d1e6998-6aaf-4de8-b74b-e97ef8bb7b63" start_index="0" end="1aa3923b-3a38-4ed6-9f07-6d7fd3bf6ae3" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9d1e6998-6aaf-4de8-b74b-e97ef8bb7b63" start_index="0" end="ff837d9d-d0b4-418a-b799-11716c69ebea" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>