<Workspace Version="1.3.2.2480" X="15.1999999999999" Y="153.6" zoom="1" ScaleFactor="1" Name="CreatDuctsByModelCurves" Description="Create ducts by model curves and family type." ID="0178228c-2b6f-44a0-b5f9-543cb664e26d" Category="Quasar.RevitNodes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="20abfad1-3a1a-45b4-9809-5a2a5096dd61" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script># dynamo version - 1.3.2'
# author - min.naung/mgjean @https://twentytwo.space/contact
import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from Autodesk.Revit.DB.Mechanical import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument;

lines = IN[0];
ductType = UnwrapElement(IN[1]);

ducts = [];

# list 
if isinstance(lines, list):
	lines = UnwrapElement(lines);
else:
	lines = UnwrapElement([lines]);

#current view level
level = doc.ActiveView.GenLevel;

#collect family symbol
fsymbol = FilteredElementCollector(doc).OfClass(MechanicalSystemType).ToElements()[0];


#transaction start
TransactionManager.Instance.EnsureInTransaction(doc);

for line in lines:
	
	#create duct
	duct = Duct.Create(doc, fsymbol.Id,ductType.Id, level.Id, line.GeometryCurve.GetEndPoint(0), line.GeometryCurve.GetEndPoint(1));	
	ducts.append(duct);

#transaction end
TransactionManager.Instance.TransactionTaskDone();

OUT = ducts</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="bef19d51-035a-4fe5-af05-0ba0af8ab9dc" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Model curves&#xD;&#xA;ModelCurves;" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="55dcc035-dfd9-448f-a750-9060aadaa73d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Duct Family Type&#xD;&#xA;familyType" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="506b7597-b1f9-442d-82cd-50acd59c4bfb" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Return Elements&#xD;&#xA;Ducts" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="20abfad1-3a1a-45b4-9809-5a2a5096dd61" start_index="0" end="506b7597-b1f9-442d-82cd-50acd59c4bfb" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="bef19d51-035a-4fe5-af05-0ba0af8ab9dc" start_index="0" end="20abfad1-3a1a-45b4-9809-5a2a5096dd61" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="55dcc035-dfd9-448f-a750-9060aadaa73d" start_index="0" end="20abfad1-3a1a-45b4-9809-5a2a5096dd61" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="6103.71337890625" eyeY="9567.5751953125" eyeZ="1886.18872070313" lookX="-18.0920925140381" lookY="-9644.0234375" lookZ="-542.342468261719" upX="-0.0321124345064163" upY="0.268919825553894" upZ="-0.962627112865448" />
  </Cameras>
</Workspace>