<Workspace Version="1.3.2.2480" X="14.4" Y="161.6" zoom="1" ScaleFactor="1" Name="WallPaintRemove" Description="Remove paint from input walls" ID="01770292-2e3b-4d86-9f84-e9204bb6cd49" Category="Quasar.RevitNodes">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="1ee43fb1-a448-4bb0-8af5-b972bb6b1374" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2
# author - min.naung/mgjean @https://twentytwo.space/contact

import clr
clr.AddReference("RevitAPI")
clr.AddReference("RevitServices")

from Autodesk.Revit.DB import *
from RevitServices.Transactions import TransactionManager
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument;
TransactionManager.Instance.EnsureInTransaction(doc);

walls = IN[0];

if not isinstance(walls, list):
	walls = UnwrapElement([walls]);
else:	
	walls = UnwrapElement(walls);

for i in walls:
	geoelem = i.GetGeometryObjectFromReference(Reference(i))
	geoobj = geoelem.GetEnumerator();
	for obj in geoobj:
		for f in obj.Faces:
			doc.RemovePaint(i.Id,f);

TransactionManager.Instance.TransactionTaskDone();	
			

OUT = walls;</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="0070f914-7205-4bd0-bfcc-6c5641dc058c" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// Return non paint wall elements&#xD;&#xA;Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="c9a69c0a-aa25-4c4d-9061-0f971db6698d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="4.80000000000013" y="4" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="// Wall elements&#xD;&#xA;Walls" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="1ee43fb1-a448-4bb0-8af5-b972bb6b1374" start_index="0" end="0070f914-7205-4bd0-bfcc-6c5641dc058c" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c9a69c0a-aa25-4c4d-9061-0f971db6698d" start_index="0" end="1ee43fb1-a448-4bb0-8af5-b972bb6b1374" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>