<Workspace Version="1.3.0.875" X="306.31017216624" Y="194.273132196984" zoom="0.931811528498331" ScaleFactor="1" Name="3DViewsSectionBoxesByRooms" Description="Create 3DViews with section boxes by room elements and offset." ID="15438529-6c69-45a0-8f24-36686811efd9" Category="Quasar.Revit.AxonometricView">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.List" resolvedName="DSCore.List" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="46e09d3e-ed3c-4ba2-a686-019cb2302b99" type="PythonNodeModels.PythonNode" nickname="SectionBoxes3DViewsByElements" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="4">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <PortInfo index="3" default="False" />
      <Script># dynamo version - 1.3.0
# author - mgjean
import clr
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument

listElements = IN[0];
listViewNames = IN[1];
offset = IN[2]/304.8;
run = IN[3];
results = [];

if not isinstance(listElements,list):
	listElements = [listElements];

if not isinstance(listViewNames,list):
	listViewNames = [listViewNames];


def crop_box(bbox, offset):
	minX = bbox.Min.X - offset;
	minY = bbox.Min.Y - offset;
	minZ = bbox.Min.Z - offset;
	maxX = bbox.Max.X + offset;
	maxY = bbox.Max.Y + offset;
	maxZ = bbox.Max.Z + offset;
	
	newbox = BoundingBoxXYZ();
	newbox.Min = XYZ(minX,minY, minZ);
	newbox.Max = XYZ(maxX, maxY, maxZ);
	return newbox;

def createNewSectionBox(elem,viewName,offset):

	collector = FilteredElementCollector(doc).OfClass(ViewFamilyType);
	for i in collector:
		if i.ViewFamily == ViewFamily.ThreeDimensional:
			viewType = i;	
	
	bbox = crop_box(UnwrapElement(elem).BoundingBox[doc.ActiveView],offset);
	
	# create 3D View
	view = View3D.CreateIsometric(doc, viewType.Id);
	view.Name = viewName;
	view.SetSectionBox(bbox);
	view.CropBoxActive = True;
	view.CropBoxVisible = True;
	view.Scale = 50;
	view.DetailLevel = ViewDetailLevel.Fine;
	view.DisplayStyle = DisplayStyle.Realistic;
	# return view
	return view;

if run:

	# Start Transaction
	TransactionManager.Instance.EnsureInTransaction(doc);

	for element,name in zip(listElements,listViewNames):
		results.append(createNewSectionBox(element,name,offset));
	
	# End Transaction
	TransactionManager.Instance.TransactionTaskDone()

	OUT = results;
else:
	OUT = "Run Forest Run";</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="d1f2bdb5-4e78-4b3f-95e4-3d0c51afd720" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Rooms" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="a3d6e7d9-8eb6-432d-a2ce-8dbc4d978a03" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Names:string" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="50197058-f3f1-479e-a22c-cb4e5e1ba8f0" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-41.9998209856278" y="243.920089846528" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Offset:double" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="89cabbb6-0148-464e-8225-8d329196aead" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="9.72726396092776" y="355.380250561884" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Run:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="e154a998-9b48-4cd0-9471-9e90eea4c121" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="545" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="3DViews" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="46e09d3e-ed3c-4ba2-a686-019cb2302b99" start_index="0" end="e154a998-9b48-4cd0-9471-9e90eea4c121" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d1f2bdb5-4e78-4b3f-95e4-3d0c51afd720" start_index="0" end="46e09d3e-ed3c-4ba2-a686-019cb2302b99" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a3d6e7d9-8eb6-432d-a2ce-8dbc4d978a03" start_index="0" end="46e09d3e-ed3c-4ba2-a686-019cb2302b99" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="50197058-f3f1-479e-a22c-cb4e5e1ba8f0" start_index="0" end="46e09d3e-ed3c-4ba2-a686-019cb2302b99" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="89cabbb6-0148-464e-8225-8d329196aead" start_index="0" end="46e09d3e-ed3c-4ba2-a686-019cb2302b99" end_index="3" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="88c067c6-61d9-4bd9-bf54-09008f97edb8" text="IN[0] = Room elements;&#xD;&#xA;IN[1] = Names for views&#xD;&#xA;IN[2] = Offset from element bounding box ( Unit : millimeters)&#xD;&#xA;IN[4] = Run" x="237.89926994054" y="-108.970826602866" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>