<Workspace Version="1.3.0.875" X="-79.4707335583153" Y="121.017045059395" zoom="1.33823125" ScaleFactor="1" Name="FamilyAndRoomByLevel" Description="This node return families instances inside each rooms by their associate level." ID="61b4ffe4-9fd8-4c03-a89c-c1b295856bf7" Category="Quasar.Revit.Room">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="2c104f83-340a-428e-a80a-19c784e48faa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="261.956080087055" y="26.9011801958742" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version 1.3.0 
# author - mgjean 

import clr
clr.AddReference("RevitAPI")
from Autodesk.Revit.DB import *
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument

run = IN[0];
if run:
	rooms = FilteredElementCollector(doc).OfCategory(BuiltInCategory.OST_Rooms);
	levels = FilteredElementCollector(doc).OfClass(Level).ToElements();
	familyInstances = FilteredElementCollector(doc).OfClass(FamilyInstance).ToElements();
	result = [];
	final = [];

	for r in rooms:
		sub = [r];
		for fm in familyInstances:
			if r.IsPointInRoom(fm.Location.Point):
				sub.append(fm);
		result.append(sub);

	for lvl in levels:
		newsub = [lvl];
		for res in result:
			if lvl.Id == res[0].LevelId:
				newsub.append(res);
		final.append(newsub);
	
	OUT = final;
else:
	OUT = "Run Forest Run";</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="6b737759-c780-41b5-8aea-4362e7456a07" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="ListElements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0c569022-482d-4616-8659-32c55e87ccd6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="72.0882385300114" y="1.48177300493074" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="Run:bool=false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="2c104f83-340a-428e-a80a-19c784e48faa" start_index="0" end="6b737759-c780-41b5-8aea-4362e7456a07" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0c569022-482d-4616-8659-32c55e87ccd6" start_index="0" end="2c104f83-340a-428e-a80a-19c784e48faa" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>