<Workspace Version="1.3.2.2480" X="-120" Y="188" zoom="1" ScaleFactor="1" Name="GetAllWorksets" Description="Collect all user created worksets from current document." ID="71cef8ca-325e-4d0b-80df-1a6f349e3093" Category="Quasar.ElementUtility">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="388d3bd6-bd28-4fd7-9fbb-9ee0f1c6ad43" type="PythonNodeModels.PythonNode" nickname="Python Script" x="194.8" y="-48" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="0">
      <Script># dynamo version - 1.3.2
# author - min.naung/mgjean https://twentytwo.space/contact/

import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import Autodesk

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument

# collect user created worksets
worksets = FilteredWorksetCollector(doc).OfKind(WorksetKind.UserWorkset).ToWorksets()

# return list structure [[name,workset],[]...[]]
OUT = [[i.Name,i] for i in worksets]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="93561823-0a97-4f3c-a5ed-3a78a29d3573" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="377" y="-69.6" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="//return list structure [[name,workset],[]...[]]&#xD;&#xA;NameAndWorkset;" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="388d3bd6-bd28-4fd7-9fbb-9ee0f1c6ad43" start_index="0" end="93561823-0a97-4f3c-a5ed-3a78a29d3573" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>