<Workspace Version="1.3.2.2480" X="137.882" Y="192.748" zoom="0.8425" ScaleFactor="1" Name="RoomTagToRoom" Description="Relocate room tag to associate room location" ID="f1b554a7-c089-4113-80bb-2459ffbcfa9b" Category="Quasar.RoomUtility">
  <NamespaceResolutionMap>
    <ClassMap partialName="Math" resolvedName="DSCore.Math" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="08cbb8b9-cf8b-4c3e-8cb7-0a0718419ca7" type="PythonNodeModels.PythonNode" nickname="CenterRoomTag" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script># dynamo version - 1.3.2
# author - min.naung/mgjean https://twentytwo.space/contact/

import clr

#clr.AddReference('RevitAPI')
clr.AddReference('RevitServices')

#from Autodesk.Revit.DB import *
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument

elems = IN[0];

if not isinstance(elems,list):
	elems = UnwrapElement([elem])
else:
	elems = UnwrapElement(elems)

#room_tags = FilteredElementCollector(doc).OfClass(SpatialElementTag).ToElements()


TransactionManager.Instance.EnsureInTransaction(doc)

for i in elems:
	room_loc = i.Room.Location.Point
	new_loc = room_loc - i.Location.Point
	i.Location.Move(new_loc)

TransactionManager.Instance.TransactionTaskDone()

OUT = elems




















</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="37dea661-833c-4f7a-b27a-d2d0423326a2" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//Room Tags Elements&#xD;&#xA;RoomTags" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="7207c1a2-71e1-4c41-bca1-2d5ce41d1184" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="449.8" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="// return elements&#xD;&#xA;Elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="08cbb8b9-cf8b-4c3e-8cb7-0a0718419ca7" start_index="0" end="7207c1a2-71e1-4c41-bca1-2d5ce41d1184" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="37dea661-833c-4f7a-b27a-d2d0423326a2" start_index="0" end="08cbb8b9-cf8b-4c3e-8cb7-0a0718419ca7" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-14706.494140625" eyeY="10518.173828125" eyeZ="8834.8251953125" lookX="12200.14453125" lookY="-12437.59765625" lookZ="-6905.49853515625" upX="0.424566835165024" upY="0.87292206287384" upZ="-0.240312352776527" />
  </Cameras>
</Workspace>